// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"ztna-core/edge-api/rest_model"
)

// EnrollUpdbReader is a Reader for the EnrollUpdb structure.
type EnrollUpdbReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnrollUpdbReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewEnrollUpdbOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewEnrollUpdbNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewEnrollUpdbTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEnrollUpdbServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /enroll/updb] enrollUpdb", response, response.Code())
	}
}

// NewEnrollUpdbOK creates a EnrollUpdbOK with default headers values
func NewEnrollUpdbOK() *EnrollUpdbOK {
    logtrace.LogWithFunctionName()
	return &EnrollUpdbOK{}
}

/*
EnrollUpdbOK describes a response with status code 200, with default header values.

Base empty response
*/
type EnrollUpdbOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this enroll updb o k response has a 2xx status code
func (o *EnrollUpdbOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this enroll updb o k response has a 3xx status code
func (o *EnrollUpdbOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll updb o k response has a 4xx status code
func (o *EnrollUpdbOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enroll updb o k response has a 5xx status code
func (o *EnrollUpdbOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enroll updb o k response a status code equal to that given
func (o *EnrollUpdbOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the enroll updb o k response
func (o *EnrollUpdbOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *EnrollUpdbOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbOK %s", 200, payload)
}

func (o *EnrollUpdbOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbOK %s", 200, payload)
}

func (o *EnrollUpdbOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollUpdbOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollUpdbNotFound creates a EnrollUpdbNotFound with default headers values
func NewEnrollUpdbNotFound() *EnrollUpdbNotFound {
    logtrace.LogWithFunctionName()
	return &EnrollUpdbNotFound{}
}

/*
EnrollUpdbNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type EnrollUpdbNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enroll updb not found response has a 2xx status code
func (o *EnrollUpdbNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enroll updb not found response has a 3xx status code
func (o *EnrollUpdbNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll updb not found response has a 4xx status code
func (o *EnrollUpdbNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enroll updb not found response has a 5xx status code
func (o *EnrollUpdbNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enroll updb not found response a status code equal to that given
func (o *EnrollUpdbNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the enroll updb not found response
func (o *EnrollUpdbNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *EnrollUpdbNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbNotFound %s", 404, payload)
}

func (o *EnrollUpdbNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbNotFound %s", 404, payload)
}

func (o *EnrollUpdbNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollUpdbNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollUpdbTooManyRequests creates a EnrollUpdbTooManyRequests with default headers values
func NewEnrollUpdbTooManyRequests() *EnrollUpdbTooManyRequests {
    logtrace.LogWithFunctionName()
	return &EnrollUpdbTooManyRequests{}
}

/*
EnrollUpdbTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type EnrollUpdbTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enroll updb too many requests response has a 2xx status code
func (o *EnrollUpdbTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enroll updb too many requests response has a 3xx status code
func (o *EnrollUpdbTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll updb too many requests response has a 4xx status code
func (o *EnrollUpdbTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enroll updb too many requests response has a 5xx status code
func (o *EnrollUpdbTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enroll updb too many requests response a status code equal to that given
func (o *EnrollUpdbTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the enroll updb too many requests response
func (o *EnrollUpdbTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *EnrollUpdbTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbTooManyRequests %s", 429, payload)
}

func (o *EnrollUpdbTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbTooManyRequests %s", 429, payload)
}

func (o *EnrollUpdbTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollUpdbTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollUpdbServiceUnavailable creates a EnrollUpdbServiceUnavailable with default headers values
func NewEnrollUpdbServiceUnavailable() *EnrollUpdbServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &EnrollUpdbServiceUnavailable{}
}

/*
EnrollUpdbServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type EnrollUpdbServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enroll updb service unavailable response has a 2xx status code
func (o *EnrollUpdbServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enroll updb service unavailable response has a 3xx status code
func (o *EnrollUpdbServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll updb service unavailable response has a 4xx status code
func (o *EnrollUpdbServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enroll updb service unavailable response has a 5xx status code
func (o *EnrollUpdbServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this enroll updb service unavailable response a status code equal to that given
func (o *EnrollUpdbServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the enroll updb service unavailable response
func (o *EnrollUpdbServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *EnrollUpdbServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbServiceUnavailable %s", 503, payload)
}

func (o *EnrollUpdbServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/updb][%d] enrollUpdbServiceUnavailable %s", 503, payload)
}

func (o *EnrollUpdbServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollUpdbServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
EnrollUpdbBody enroll updb body
swagger:model EnrollUpdbBody
*/
type EnrollUpdbBody struct {

	// password
	Password rest_model.Password `json:"password,omitempty"`

	// username
	Username rest_model.Username `json:"username,omitempty"`
}

// Validate validates this enroll updb body
func (o *EnrollUpdbBody) Validate(formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()
	var res []error

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EnrollUpdbBody) validatePassword(formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()
	if swag.IsZero(o.Password) { // not required
		return nil
	}

	if err := o.Password.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updbCredentials" + "." + "password")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updbCredentials" + "." + "password")
		}
		return err
	}

	return nil
}

func (o *EnrollUpdbBody) validateUsername(formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()
	if swag.IsZero(o.Username) { // not required
		return nil
	}

	if err := o.Username.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updbCredentials" + "." + "username")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updbCredentials" + "." + "username")
		}
		return err
	}

	return nil
}

// ContextValidate validate this enroll updb body based on the context it is used
func (o *EnrollUpdbBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()
	var res []error

	if err := o.contextValidatePassword(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateUsername(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EnrollUpdbBody) contextValidatePassword(ctx context.Context, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	if swag.IsZero(o.Password) { // not required
		return nil
	}

	if err := o.Password.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updbCredentials" + "." + "password")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updbCredentials" + "." + "password")
		}
		return err
	}

	return nil
}

func (o *EnrollUpdbBody) contextValidateUsername(ctx context.Context, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	if swag.IsZero(o.Username) { // not required
		return nil
	}

	if err := o.Username.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updbCredentials" + "." + "username")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updbCredentials" + "." + "username")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *EnrollUpdbBody) MarshalBinary() ([]byte, error) {
    logtrace.LogWithFunctionName()
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *EnrollUpdbBody) UnmarshalBinary(b []byte) error {
    logtrace.LogWithFunctionName()
	var res EnrollUpdbBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
