// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// EnrollOttCaReader is a Reader for the EnrollOttCa structure.
type EnrollOttCaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnrollOttCaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewEnrollOttCaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewEnrollOttCaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEnrollOttCaServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /enroll/ottca] enrollOttCa", response, response.Code())
	}
}

// NewEnrollOttCaOK creates a EnrollOttCaOK with default headers values
func NewEnrollOttCaOK() *EnrollOttCaOK {
    logtrace.LogWithFunctionName()
	return &EnrollOttCaOK{}
}

/*
EnrollOttCaOK describes a response with status code 200, with default header values.

Base empty response
*/
type EnrollOttCaOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this enroll ott ca o k response has a 2xx status code
func (o *EnrollOttCaOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this enroll ott ca o k response has a 3xx status code
func (o *EnrollOttCaOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll ott ca o k response has a 4xx status code
func (o *EnrollOttCaOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enroll ott ca o k response has a 5xx status code
func (o *EnrollOttCaOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enroll ott ca o k response a status code equal to that given
func (o *EnrollOttCaOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the enroll ott ca o k response
func (o *EnrollOttCaOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *EnrollOttCaOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaOK %s", 200, payload)
}

func (o *EnrollOttCaOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaOK %s", 200, payload)
}

func (o *EnrollOttCaOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollOttCaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollOttCaTooManyRequests creates a EnrollOttCaTooManyRequests with default headers values
func NewEnrollOttCaTooManyRequests() *EnrollOttCaTooManyRequests {
    logtrace.LogWithFunctionName()
	return &EnrollOttCaTooManyRequests{}
}

/*
EnrollOttCaTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type EnrollOttCaTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enroll ott ca too many requests response has a 2xx status code
func (o *EnrollOttCaTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enroll ott ca too many requests response has a 3xx status code
func (o *EnrollOttCaTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll ott ca too many requests response has a 4xx status code
func (o *EnrollOttCaTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enroll ott ca too many requests response has a 5xx status code
func (o *EnrollOttCaTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enroll ott ca too many requests response a status code equal to that given
func (o *EnrollOttCaTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the enroll ott ca too many requests response
func (o *EnrollOttCaTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *EnrollOttCaTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaTooManyRequests %s", 429, payload)
}

func (o *EnrollOttCaTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaTooManyRequests %s", 429, payload)
}

func (o *EnrollOttCaTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollOttCaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnrollOttCaServiceUnavailable creates a EnrollOttCaServiceUnavailable with default headers values
func NewEnrollOttCaServiceUnavailable() *EnrollOttCaServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &EnrollOttCaServiceUnavailable{}
}

/*
EnrollOttCaServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type EnrollOttCaServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enroll ott ca service unavailable response has a 2xx status code
func (o *EnrollOttCaServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enroll ott ca service unavailable response has a 3xx status code
func (o *EnrollOttCaServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enroll ott ca service unavailable response has a 4xx status code
func (o *EnrollOttCaServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enroll ott ca service unavailable response has a 5xx status code
func (o *EnrollOttCaServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this enroll ott ca service unavailable response a status code equal to that given
func (o *EnrollOttCaServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the enroll ott ca service unavailable response
func (o *EnrollOttCaServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *EnrollOttCaServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaServiceUnavailable %s", 503, payload)
}

func (o *EnrollOttCaServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /enroll/ottca][%d] enrollOttCaServiceUnavailable %s", 503, payload)
}

func (o *EnrollOttCaServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnrollOttCaServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
