// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package auth_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// CreateAuthPolicyReader is a Reader for the CreateAuthPolicy structure.
type CreateAuthPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAuthPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 201:
		result := NewCreateAuthPolicyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAuthPolicyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateAuthPolicyUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCreateAuthPolicyTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewCreateAuthPolicyServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /auth-policies] createAuthPolicy", response, response.Code())
	}
}

// NewCreateAuthPolicyCreated creates a CreateAuthPolicyCreated with default headers values
func NewCreateAuthPolicyCreated() *CreateAuthPolicyCreated {
    logtrace.LogWithFunctionName()
	return &CreateAuthPolicyCreated{}
}

/*
CreateAuthPolicyCreated describes a response with status code 201, with default header values.

The create request was successful and the resource has been added at the following location
*/
type CreateAuthPolicyCreated struct {
	Payload *rest_model.CreateEnvelope
}

// IsSuccess returns true when this create auth policy created response has a 2xx status code
func (o *CreateAuthPolicyCreated) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this create auth policy created response has a 3xx status code
func (o *CreateAuthPolicyCreated) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create auth policy created response has a 4xx status code
func (o *CreateAuthPolicyCreated) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this create auth policy created response has a 5xx status code
func (o *CreateAuthPolicyCreated) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create auth policy created response a status code equal to that given
func (o *CreateAuthPolicyCreated) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 201
}

// Code gets the status code for the create auth policy created response
func (o *CreateAuthPolicyCreated) Code() int {
    logtrace.LogWithFunctionName()
	return 201
}

func (o *CreateAuthPolicyCreated) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyCreated %s", 201, payload)
}

func (o *CreateAuthPolicyCreated) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyCreated %s", 201, payload)
}

func (o *CreateAuthPolicyCreated) GetPayload() *rest_model.CreateEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateAuthPolicyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.CreateEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthPolicyBadRequest creates a CreateAuthPolicyBadRequest with default headers values
func NewCreateAuthPolicyBadRequest() *CreateAuthPolicyBadRequest {
    logtrace.LogWithFunctionName()
	return &CreateAuthPolicyBadRequest{}
}

/*
CreateAuthPolicyBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type CreateAuthPolicyBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create auth policy bad request response has a 2xx status code
func (o *CreateAuthPolicyBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create auth policy bad request response has a 3xx status code
func (o *CreateAuthPolicyBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create auth policy bad request response has a 4xx status code
func (o *CreateAuthPolicyBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create auth policy bad request response has a 5xx status code
func (o *CreateAuthPolicyBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create auth policy bad request response a status code equal to that given
func (o *CreateAuthPolicyBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the create auth policy bad request response
func (o *CreateAuthPolicyBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *CreateAuthPolicyBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyBadRequest %s", 400, payload)
}

func (o *CreateAuthPolicyBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyBadRequest %s", 400, payload)
}

func (o *CreateAuthPolicyBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateAuthPolicyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthPolicyUnauthorized creates a CreateAuthPolicyUnauthorized with default headers values
func NewCreateAuthPolicyUnauthorized() *CreateAuthPolicyUnauthorized {
    logtrace.LogWithFunctionName()
	return &CreateAuthPolicyUnauthorized{}
}

/*
CreateAuthPolicyUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type CreateAuthPolicyUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create auth policy unauthorized response has a 2xx status code
func (o *CreateAuthPolicyUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create auth policy unauthorized response has a 3xx status code
func (o *CreateAuthPolicyUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create auth policy unauthorized response has a 4xx status code
func (o *CreateAuthPolicyUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create auth policy unauthorized response has a 5xx status code
func (o *CreateAuthPolicyUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create auth policy unauthorized response a status code equal to that given
func (o *CreateAuthPolicyUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the create auth policy unauthorized response
func (o *CreateAuthPolicyUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *CreateAuthPolicyUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyUnauthorized %s", 401, payload)
}

func (o *CreateAuthPolicyUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyUnauthorized %s", 401, payload)
}

func (o *CreateAuthPolicyUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateAuthPolicyUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthPolicyTooManyRequests creates a CreateAuthPolicyTooManyRequests with default headers values
func NewCreateAuthPolicyTooManyRequests() *CreateAuthPolicyTooManyRequests {
    logtrace.LogWithFunctionName()
	return &CreateAuthPolicyTooManyRequests{}
}

/*
CreateAuthPolicyTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type CreateAuthPolicyTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create auth policy too many requests response has a 2xx status code
func (o *CreateAuthPolicyTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create auth policy too many requests response has a 3xx status code
func (o *CreateAuthPolicyTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create auth policy too many requests response has a 4xx status code
func (o *CreateAuthPolicyTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create auth policy too many requests response has a 5xx status code
func (o *CreateAuthPolicyTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create auth policy too many requests response a status code equal to that given
func (o *CreateAuthPolicyTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the create auth policy too many requests response
func (o *CreateAuthPolicyTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *CreateAuthPolicyTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyTooManyRequests %s", 429, payload)
}

func (o *CreateAuthPolicyTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyTooManyRequests %s", 429, payload)
}

func (o *CreateAuthPolicyTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateAuthPolicyTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthPolicyServiceUnavailable creates a CreateAuthPolicyServiceUnavailable with default headers values
func NewCreateAuthPolicyServiceUnavailable() *CreateAuthPolicyServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &CreateAuthPolicyServiceUnavailable{}
}

/*
CreateAuthPolicyServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type CreateAuthPolicyServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create auth policy service unavailable response has a 2xx status code
func (o *CreateAuthPolicyServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create auth policy service unavailable response has a 3xx status code
func (o *CreateAuthPolicyServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create auth policy service unavailable response has a 4xx status code
func (o *CreateAuthPolicyServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this create auth policy service unavailable response has a 5xx status code
func (o *CreateAuthPolicyServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this create auth policy service unavailable response a status code equal to that given
func (o *CreateAuthPolicyServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the create auth policy service unavailable response
func (o *CreateAuthPolicyServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *CreateAuthPolicyServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyServiceUnavailable %s", 503, payload)
}

func (o *CreateAuthPolicyServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /auth-policies][%d] createAuthPolicyServiceUnavailable %s", 503, payload)
}

func (o *CreateAuthPolicyServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateAuthPolicyServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
