// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package posture_checks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListPostureCheckTypesReader is a Reader for the ListPostureCheckTypes structure.
type ListPostureCheckTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPostureCheckTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListPostureCheckTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListPostureCheckTypesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListPostureCheckTypesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListPostureCheckTypesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListPostureCheckTypesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /posture-check-types] listPostureCheckTypes", response, response.Code())
	}
}

// NewListPostureCheckTypesOK creates a ListPostureCheckTypesOK with default headers values
func NewListPostureCheckTypesOK() *ListPostureCheckTypesOK {
    logtrace.LogWithFunctionName()
	return &ListPostureCheckTypesOK{}
}

/*
ListPostureCheckTypesOK describes a response with status code 200, with default header values.

A list of posture check types
*/
type ListPostureCheckTypesOK struct {
	Payload *rest_model.ListPostureCheckTypesEnvelope
}

// IsSuccess returns true when this list posture check types o k response has a 2xx status code
func (o *ListPostureCheckTypesOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list posture check types o k response has a 3xx status code
func (o *ListPostureCheckTypesOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list posture check types o k response has a 4xx status code
func (o *ListPostureCheckTypesOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list posture check types o k response has a 5xx status code
func (o *ListPostureCheckTypesOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list posture check types o k response a status code equal to that given
func (o *ListPostureCheckTypesOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list posture check types o k response
func (o *ListPostureCheckTypesOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListPostureCheckTypesOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesOK %s", 200, payload)
}

func (o *ListPostureCheckTypesOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesOK %s", 200, payload)
}

func (o *ListPostureCheckTypesOK) GetPayload() *rest_model.ListPostureCheckTypesEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListPostureCheckTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListPostureCheckTypesEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPostureCheckTypesBadRequest creates a ListPostureCheckTypesBadRequest with default headers values
func NewListPostureCheckTypesBadRequest() *ListPostureCheckTypesBadRequest {
    logtrace.LogWithFunctionName()
	return &ListPostureCheckTypesBadRequest{}
}

/*
ListPostureCheckTypesBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type ListPostureCheckTypesBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list posture check types bad request response has a 2xx status code
func (o *ListPostureCheckTypesBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list posture check types bad request response has a 3xx status code
func (o *ListPostureCheckTypesBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list posture check types bad request response has a 4xx status code
func (o *ListPostureCheckTypesBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list posture check types bad request response has a 5xx status code
func (o *ListPostureCheckTypesBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list posture check types bad request response a status code equal to that given
func (o *ListPostureCheckTypesBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the list posture check types bad request response
func (o *ListPostureCheckTypesBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *ListPostureCheckTypesBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesBadRequest %s", 400, payload)
}

func (o *ListPostureCheckTypesBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesBadRequest %s", 400, payload)
}

func (o *ListPostureCheckTypesBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListPostureCheckTypesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPostureCheckTypesUnauthorized creates a ListPostureCheckTypesUnauthorized with default headers values
func NewListPostureCheckTypesUnauthorized() *ListPostureCheckTypesUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListPostureCheckTypesUnauthorized{}
}

/*
ListPostureCheckTypesUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListPostureCheckTypesUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list posture check types unauthorized response has a 2xx status code
func (o *ListPostureCheckTypesUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list posture check types unauthorized response has a 3xx status code
func (o *ListPostureCheckTypesUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list posture check types unauthorized response has a 4xx status code
func (o *ListPostureCheckTypesUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list posture check types unauthorized response has a 5xx status code
func (o *ListPostureCheckTypesUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list posture check types unauthorized response a status code equal to that given
func (o *ListPostureCheckTypesUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list posture check types unauthorized response
func (o *ListPostureCheckTypesUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListPostureCheckTypesUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesUnauthorized %s", 401, payload)
}

func (o *ListPostureCheckTypesUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesUnauthorized %s", 401, payload)
}

func (o *ListPostureCheckTypesUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListPostureCheckTypesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPostureCheckTypesTooManyRequests creates a ListPostureCheckTypesTooManyRequests with default headers values
func NewListPostureCheckTypesTooManyRequests() *ListPostureCheckTypesTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListPostureCheckTypesTooManyRequests{}
}

/*
ListPostureCheckTypesTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListPostureCheckTypesTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list posture check types too many requests response has a 2xx status code
func (o *ListPostureCheckTypesTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list posture check types too many requests response has a 3xx status code
func (o *ListPostureCheckTypesTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list posture check types too many requests response has a 4xx status code
func (o *ListPostureCheckTypesTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list posture check types too many requests response has a 5xx status code
func (o *ListPostureCheckTypesTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list posture check types too many requests response a status code equal to that given
func (o *ListPostureCheckTypesTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list posture check types too many requests response
func (o *ListPostureCheckTypesTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListPostureCheckTypesTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesTooManyRequests %s", 429, payload)
}

func (o *ListPostureCheckTypesTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesTooManyRequests %s", 429, payload)
}

func (o *ListPostureCheckTypesTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListPostureCheckTypesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPostureCheckTypesServiceUnavailable creates a ListPostureCheckTypesServiceUnavailable with default headers values
func NewListPostureCheckTypesServiceUnavailable() *ListPostureCheckTypesServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListPostureCheckTypesServiceUnavailable{}
}

/*
ListPostureCheckTypesServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListPostureCheckTypesServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list posture check types service unavailable response has a 2xx status code
func (o *ListPostureCheckTypesServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list posture check types service unavailable response has a 3xx status code
func (o *ListPostureCheckTypesServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list posture check types service unavailable response has a 4xx status code
func (o *ListPostureCheckTypesServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list posture check types service unavailable response has a 5xx status code
func (o *ListPostureCheckTypesServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list posture check types service unavailable response a status code equal to that given
func (o *ListPostureCheckTypesServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list posture check types service unavailable response
func (o *ListPostureCheckTypesServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListPostureCheckTypesServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesServiceUnavailable %s", 503, payload)
}

func (o *ListPostureCheckTypesServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /posture-check-types][%d] listPostureCheckTypesServiceUnavailable %s", 503, payload)
}

func (o *ListPostureCheckTypesServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListPostureCheckTypesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
