// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package external_jwt_signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListExternalJWTSignersReader is a Reader for the ListExternalJWTSigners structure.
type ListExternalJWTSignersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListExternalJWTSignersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListExternalJWTSignersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListExternalJWTSignersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListExternalJWTSignersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListExternalJWTSignersTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListExternalJWTSignersServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /external-jwt-signers] listExternalJwtSigners", response, response.Code())
	}
}

// NewListExternalJWTSignersOK creates a ListExternalJWTSignersOK with default headers values
func NewListExternalJWTSignersOK() *ListExternalJWTSignersOK {
    logtrace.LogWithFunctionName()
	return &ListExternalJWTSignersOK{}
}

/*
ListExternalJWTSignersOK describes a response with status code 200, with default header values.

A list of External JWT Signers
*/
type ListExternalJWTSignersOK struct {
	Payload *rest_model.ListClientExternalJWTSignersEnvelope
}

// IsSuccess returns true when this list external Jwt signers o k response has a 2xx status code
func (o *ListExternalJWTSignersOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list external Jwt signers o k response has a 3xx status code
func (o *ListExternalJWTSignersOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list external Jwt signers o k response has a 4xx status code
func (o *ListExternalJWTSignersOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list external Jwt signers o k response has a 5xx status code
func (o *ListExternalJWTSignersOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list external Jwt signers o k response a status code equal to that given
func (o *ListExternalJWTSignersOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list external Jwt signers o k response
func (o *ListExternalJWTSignersOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListExternalJWTSignersOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersOK %s", 200, payload)
}

func (o *ListExternalJWTSignersOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersOK %s", 200, payload)
}

func (o *ListExternalJWTSignersOK) GetPayload() *rest_model.ListClientExternalJWTSignersEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListExternalJWTSignersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListClientExternalJWTSignersEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListExternalJWTSignersBadRequest creates a ListExternalJWTSignersBadRequest with default headers values
func NewListExternalJWTSignersBadRequest() *ListExternalJWTSignersBadRequest {
    logtrace.LogWithFunctionName()
	return &ListExternalJWTSignersBadRequest{}
}

/*
ListExternalJWTSignersBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type ListExternalJWTSignersBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list external Jwt signers bad request response has a 2xx status code
func (o *ListExternalJWTSignersBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list external Jwt signers bad request response has a 3xx status code
func (o *ListExternalJWTSignersBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list external Jwt signers bad request response has a 4xx status code
func (o *ListExternalJWTSignersBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list external Jwt signers bad request response has a 5xx status code
func (o *ListExternalJWTSignersBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list external Jwt signers bad request response a status code equal to that given
func (o *ListExternalJWTSignersBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the list external Jwt signers bad request response
func (o *ListExternalJWTSignersBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *ListExternalJWTSignersBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersBadRequest %s", 400, payload)
}

func (o *ListExternalJWTSignersBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersBadRequest %s", 400, payload)
}

func (o *ListExternalJWTSignersBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListExternalJWTSignersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListExternalJWTSignersUnauthorized creates a ListExternalJWTSignersUnauthorized with default headers values
func NewListExternalJWTSignersUnauthorized() *ListExternalJWTSignersUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListExternalJWTSignersUnauthorized{}
}

/*
ListExternalJWTSignersUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListExternalJWTSignersUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list external Jwt signers unauthorized response has a 2xx status code
func (o *ListExternalJWTSignersUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list external Jwt signers unauthorized response has a 3xx status code
func (o *ListExternalJWTSignersUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list external Jwt signers unauthorized response has a 4xx status code
func (o *ListExternalJWTSignersUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list external Jwt signers unauthorized response has a 5xx status code
func (o *ListExternalJWTSignersUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list external Jwt signers unauthorized response a status code equal to that given
func (o *ListExternalJWTSignersUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list external Jwt signers unauthorized response
func (o *ListExternalJWTSignersUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListExternalJWTSignersUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersUnauthorized %s", 401, payload)
}

func (o *ListExternalJWTSignersUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersUnauthorized %s", 401, payload)
}

func (o *ListExternalJWTSignersUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListExternalJWTSignersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListExternalJWTSignersTooManyRequests creates a ListExternalJWTSignersTooManyRequests with default headers values
func NewListExternalJWTSignersTooManyRequests() *ListExternalJWTSignersTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListExternalJWTSignersTooManyRequests{}
}

/*
ListExternalJWTSignersTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListExternalJWTSignersTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list external Jwt signers too many requests response has a 2xx status code
func (o *ListExternalJWTSignersTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list external Jwt signers too many requests response has a 3xx status code
func (o *ListExternalJWTSignersTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list external Jwt signers too many requests response has a 4xx status code
func (o *ListExternalJWTSignersTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list external Jwt signers too many requests response has a 5xx status code
func (o *ListExternalJWTSignersTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list external Jwt signers too many requests response a status code equal to that given
func (o *ListExternalJWTSignersTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list external Jwt signers too many requests response
func (o *ListExternalJWTSignersTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListExternalJWTSignersTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersTooManyRequests %s", 429, payload)
}

func (o *ListExternalJWTSignersTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersTooManyRequests %s", 429, payload)
}

func (o *ListExternalJWTSignersTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListExternalJWTSignersTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListExternalJWTSignersServiceUnavailable creates a ListExternalJWTSignersServiceUnavailable with default headers values
func NewListExternalJWTSignersServiceUnavailable() *ListExternalJWTSignersServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListExternalJWTSignersServiceUnavailable{}
}

/*
ListExternalJWTSignersServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListExternalJWTSignersServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list external Jwt signers service unavailable response has a 2xx status code
func (o *ListExternalJWTSignersServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list external Jwt signers service unavailable response has a 3xx status code
func (o *ListExternalJWTSignersServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list external Jwt signers service unavailable response has a 4xx status code
func (o *ListExternalJWTSignersServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list external Jwt signers service unavailable response has a 5xx status code
func (o *ListExternalJWTSignersServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list external Jwt signers service unavailable response a status code equal to that given
func (o *ListExternalJWTSignersServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list external Jwt signers service unavailable response
func (o *ListExternalJWTSignersServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListExternalJWTSignersServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersServiceUnavailable %s", 503, payload)
}

func (o *ListExternalJWTSignersServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /external-jwt-signers][%d] listExternalJwtSignersServiceUnavailable %s", 503, payload)
}

func (o *ListExternalJWTSignersServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListExternalJWTSignersServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
