// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package api_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// DeleteAPISessionsReader is a Reader for the DeleteAPISessions structure.
type DeleteAPISessionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPISessionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewDeleteAPISessionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteAPISessionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAPISessionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAPISessionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteAPISessionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteAPISessionsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api-sessions/{id}] deleteAPISessions", response, response.Code())
	}
}

// NewDeleteAPISessionsOK creates a DeleteAPISessionsOK with default headers values
func NewDeleteAPISessionsOK() *DeleteAPISessionsOK {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsOK{}
}

/*
DeleteAPISessionsOK describes a response with status code 200, with default header values.

The delete request was successful and the resource has been removed
*/
type DeleteAPISessionsOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this delete Api sessions o k response has a 2xx status code
func (o *DeleteAPISessionsOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this delete Api sessions o k response has a 3xx status code
func (o *DeleteAPISessionsOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions o k response has a 4xx status code
func (o *DeleteAPISessionsOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this delete Api sessions o k response has a 5xx status code
func (o *DeleteAPISessionsOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this delete Api sessions o k response a status code equal to that given
func (o *DeleteAPISessionsOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the delete Api sessions o k response
func (o *DeleteAPISessionsOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *DeleteAPISessionsOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsOK %s", 200, payload)
}

func (o *DeleteAPISessionsOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsOK %s", 200, payload)
}

func (o *DeleteAPISessionsOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPISessionsUnauthorized creates a DeleteAPISessionsUnauthorized with default headers values
func NewDeleteAPISessionsUnauthorized() *DeleteAPISessionsUnauthorized {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsUnauthorized{}
}

/*
DeleteAPISessionsUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type DeleteAPISessionsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this delete Api sessions unauthorized response has a 2xx status code
func (o *DeleteAPISessionsUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this delete Api sessions unauthorized response has a 3xx status code
func (o *DeleteAPISessionsUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions unauthorized response has a 4xx status code
func (o *DeleteAPISessionsUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this delete Api sessions unauthorized response has a 5xx status code
func (o *DeleteAPISessionsUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this delete Api sessions unauthorized response a status code equal to that given
func (o *DeleteAPISessionsUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the delete Api sessions unauthorized response
func (o *DeleteAPISessionsUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *DeleteAPISessionsUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsUnauthorized %s", 401, payload)
}

func (o *DeleteAPISessionsUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsUnauthorized %s", 401, payload)
}

func (o *DeleteAPISessionsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPISessionsForbidden creates a DeleteAPISessionsForbidden with default headers values
func NewDeleteAPISessionsForbidden() *DeleteAPISessionsForbidden {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsForbidden{}
}

/*
DeleteAPISessionsForbidden describes a response with status code 403, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type DeleteAPISessionsForbidden struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this delete Api sessions forbidden response has a 2xx status code
func (o *DeleteAPISessionsForbidden) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this delete Api sessions forbidden response has a 3xx status code
func (o *DeleteAPISessionsForbidden) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions forbidden response has a 4xx status code
func (o *DeleteAPISessionsForbidden) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this delete Api sessions forbidden response has a 5xx status code
func (o *DeleteAPISessionsForbidden) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this delete Api sessions forbidden response a status code equal to that given
func (o *DeleteAPISessionsForbidden) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 403
}

// Code gets the status code for the delete Api sessions forbidden response
func (o *DeleteAPISessionsForbidden) Code() int {
    logtrace.LogWithFunctionName()
	return 403
}

func (o *DeleteAPISessionsForbidden) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsForbidden %s", 403, payload)
}

func (o *DeleteAPISessionsForbidden) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsForbidden %s", 403, payload)
}

func (o *DeleteAPISessionsForbidden) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPISessionsNotFound creates a DeleteAPISessionsNotFound with default headers values
func NewDeleteAPISessionsNotFound() *DeleteAPISessionsNotFound {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsNotFound{}
}

/*
DeleteAPISessionsNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DeleteAPISessionsNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this delete Api sessions not found response has a 2xx status code
func (o *DeleteAPISessionsNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this delete Api sessions not found response has a 3xx status code
func (o *DeleteAPISessionsNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions not found response has a 4xx status code
func (o *DeleteAPISessionsNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this delete Api sessions not found response has a 5xx status code
func (o *DeleteAPISessionsNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this delete Api sessions not found response a status code equal to that given
func (o *DeleteAPISessionsNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the delete Api sessions not found response
func (o *DeleteAPISessionsNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *DeleteAPISessionsNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsNotFound %s", 404, payload)
}

func (o *DeleteAPISessionsNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsNotFound %s", 404, payload)
}

func (o *DeleteAPISessionsNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPISessionsTooManyRequests creates a DeleteAPISessionsTooManyRequests with default headers values
func NewDeleteAPISessionsTooManyRequests() *DeleteAPISessionsTooManyRequests {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsTooManyRequests{}
}

/*
DeleteAPISessionsTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type DeleteAPISessionsTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this delete Api sessions too many requests response has a 2xx status code
func (o *DeleteAPISessionsTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this delete Api sessions too many requests response has a 3xx status code
func (o *DeleteAPISessionsTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions too many requests response has a 4xx status code
func (o *DeleteAPISessionsTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this delete Api sessions too many requests response has a 5xx status code
func (o *DeleteAPISessionsTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this delete Api sessions too many requests response a status code equal to that given
func (o *DeleteAPISessionsTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the delete Api sessions too many requests response
func (o *DeleteAPISessionsTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *DeleteAPISessionsTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsTooManyRequests %s", 429, payload)
}

func (o *DeleteAPISessionsTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsTooManyRequests %s", 429, payload)
}

func (o *DeleteAPISessionsTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPISessionsServiceUnavailable creates a DeleteAPISessionsServiceUnavailable with default headers values
func NewDeleteAPISessionsServiceUnavailable() *DeleteAPISessionsServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &DeleteAPISessionsServiceUnavailable{}
}

/*
DeleteAPISessionsServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type DeleteAPISessionsServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this delete Api sessions service unavailable response has a 2xx status code
func (o *DeleteAPISessionsServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this delete Api sessions service unavailable response has a 3xx status code
func (o *DeleteAPISessionsServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this delete Api sessions service unavailable response has a 4xx status code
func (o *DeleteAPISessionsServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this delete Api sessions service unavailable response has a 5xx status code
func (o *DeleteAPISessionsServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this delete Api sessions service unavailable response a status code equal to that given
func (o *DeleteAPISessionsServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the delete Api sessions service unavailable response
func (o *DeleteAPISessionsServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *DeleteAPISessionsServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *DeleteAPISessionsServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api-sessions/{id}][%d] deleteApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *DeleteAPISessionsServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DeleteAPISessionsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
