// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package api_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// DetailAPISessionsReader is a Reader for the DetailAPISessions structure.
type DetailAPISessionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailAPISessionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewDetailAPISessionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailAPISessionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailAPISessionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDetailAPISessionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDetailAPISessionsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api-sessions/{id}] detailAPISessions", response, response.Code())
	}
}

// NewDetailAPISessionsOK creates a DetailAPISessionsOK with default headers values
func NewDetailAPISessionsOK() *DetailAPISessionsOK {
    logtrace.LogWithFunctionName()
	return &DetailAPISessionsOK{}
}

/*
DetailAPISessionsOK describes a response with status code 200, with default header values.

Retrieves a singular API Session by id
*/
type DetailAPISessionsOK struct {
	Payload *rest_model.DetailAPISessionEnvelope
}

// IsSuccess returns true when this detail Api sessions o k response has a 2xx status code
func (o *DetailAPISessionsOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this detail Api sessions o k response has a 3xx status code
func (o *DetailAPISessionsOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail Api sessions o k response has a 4xx status code
func (o *DetailAPISessionsOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail Api sessions o k response has a 5xx status code
func (o *DetailAPISessionsOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail Api sessions o k response a status code equal to that given
func (o *DetailAPISessionsOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the detail Api sessions o k response
func (o *DetailAPISessionsOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *DetailAPISessionsOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsOK %s", 200, payload)
}

func (o *DetailAPISessionsOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsOK %s", 200, payload)
}

func (o *DetailAPISessionsOK) GetPayload() *rest_model.DetailAPISessionEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailAPISessionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.DetailAPISessionEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailAPISessionsUnauthorized creates a DetailAPISessionsUnauthorized with default headers values
func NewDetailAPISessionsUnauthorized() *DetailAPISessionsUnauthorized {
    logtrace.LogWithFunctionName()
	return &DetailAPISessionsUnauthorized{}
}

/*
DetailAPISessionsUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type DetailAPISessionsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail Api sessions unauthorized response has a 2xx status code
func (o *DetailAPISessionsUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail Api sessions unauthorized response has a 3xx status code
func (o *DetailAPISessionsUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail Api sessions unauthorized response has a 4xx status code
func (o *DetailAPISessionsUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail Api sessions unauthorized response has a 5xx status code
func (o *DetailAPISessionsUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail Api sessions unauthorized response a status code equal to that given
func (o *DetailAPISessionsUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the detail Api sessions unauthorized response
func (o *DetailAPISessionsUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *DetailAPISessionsUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsUnauthorized %s", 401, payload)
}

func (o *DetailAPISessionsUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsUnauthorized %s", 401, payload)
}

func (o *DetailAPISessionsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailAPISessionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailAPISessionsNotFound creates a DetailAPISessionsNotFound with default headers values
func NewDetailAPISessionsNotFound() *DetailAPISessionsNotFound {
    logtrace.LogWithFunctionName()
	return &DetailAPISessionsNotFound{}
}

/*
DetailAPISessionsNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DetailAPISessionsNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail Api sessions not found response has a 2xx status code
func (o *DetailAPISessionsNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail Api sessions not found response has a 3xx status code
func (o *DetailAPISessionsNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail Api sessions not found response has a 4xx status code
func (o *DetailAPISessionsNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail Api sessions not found response has a 5xx status code
func (o *DetailAPISessionsNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail Api sessions not found response a status code equal to that given
func (o *DetailAPISessionsNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the detail Api sessions not found response
func (o *DetailAPISessionsNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *DetailAPISessionsNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsNotFound %s", 404, payload)
}

func (o *DetailAPISessionsNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsNotFound %s", 404, payload)
}

func (o *DetailAPISessionsNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailAPISessionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailAPISessionsTooManyRequests creates a DetailAPISessionsTooManyRequests with default headers values
func NewDetailAPISessionsTooManyRequests() *DetailAPISessionsTooManyRequests {
    logtrace.LogWithFunctionName()
	return &DetailAPISessionsTooManyRequests{}
}

/*
DetailAPISessionsTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type DetailAPISessionsTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail Api sessions too many requests response has a 2xx status code
func (o *DetailAPISessionsTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail Api sessions too many requests response has a 3xx status code
func (o *DetailAPISessionsTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail Api sessions too many requests response has a 4xx status code
func (o *DetailAPISessionsTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail Api sessions too many requests response has a 5xx status code
func (o *DetailAPISessionsTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail Api sessions too many requests response a status code equal to that given
func (o *DetailAPISessionsTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the detail Api sessions too many requests response
func (o *DetailAPISessionsTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *DetailAPISessionsTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsTooManyRequests %s", 429, payload)
}

func (o *DetailAPISessionsTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsTooManyRequests %s", 429, payload)
}

func (o *DetailAPISessionsTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailAPISessionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailAPISessionsServiceUnavailable creates a DetailAPISessionsServiceUnavailable with default headers values
func NewDetailAPISessionsServiceUnavailable() *DetailAPISessionsServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &DetailAPISessionsServiceUnavailable{}
}

/*
DetailAPISessionsServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type DetailAPISessionsServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail Api sessions service unavailable response has a 2xx status code
func (o *DetailAPISessionsServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail Api sessions service unavailable response has a 3xx status code
func (o *DetailAPISessionsServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail Api sessions service unavailable response has a 4xx status code
func (o *DetailAPISessionsServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail Api sessions service unavailable response has a 5xx status code
func (o *DetailAPISessionsServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this detail Api sessions service unavailable response a status code equal to that given
func (o *DetailAPISessionsServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the detail Api sessions service unavailable response
func (o *DetailAPISessionsServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *DetailAPISessionsServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *DetailAPISessionsServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions/{id}][%d] detailApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *DetailAPISessionsServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailAPISessionsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
