// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package api_session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListAPISessionsReader is a Reader for the ListAPISessions structure.
type ListAPISessionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAPISessionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListAPISessionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListAPISessionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListAPISessionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListAPISessionsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListAPISessionsServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api-sessions] listAPISessions", response, response.Code())
	}
}

// NewListAPISessionsOK creates a ListAPISessionsOK with default headers values
func NewListAPISessionsOK() *ListAPISessionsOK {
    logtrace.LogWithFunctionName()
	return &ListAPISessionsOK{}
}

/*
ListAPISessionsOK describes a response with status code 200, with default header values.

A list of active API Sessions
*/
type ListAPISessionsOK struct {
	Payload *rest_model.ListAPISessionsEnvelope
}

// IsSuccess returns true when this list Api sessions o k response has a 2xx status code
func (o *ListAPISessionsOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list Api sessions o k response has a 3xx status code
func (o *ListAPISessionsOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list Api sessions o k response has a 4xx status code
func (o *ListAPISessionsOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list Api sessions o k response has a 5xx status code
func (o *ListAPISessionsOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list Api sessions o k response a status code equal to that given
func (o *ListAPISessionsOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list Api sessions o k response
func (o *ListAPISessionsOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListAPISessionsOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsOK %s", 200, payload)
}

func (o *ListAPISessionsOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsOK %s", 200, payload)
}

func (o *ListAPISessionsOK) GetPayload() *rest_model.ListAPISessionsEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListAPISessionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListAPISessionsEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPISessionsBadRequest creates a ListAPISessionsBadRequest with default headers values
func NewListAPISessionsBadRequest() *ListAPISessionsBadRequest {
    logtrace.LogWithFunctionName()
	return &ListAPISessionsBadRequest{}
}

/*
ListAPISessionsBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type ListAPISessionsBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list Api sessions bad request response has a 2xx status code
func (o *ListAPISessionsBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list Api sessions bad request response has a 3xx status code
func (o *ListAPISessionsBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list Api sessions bad request response has a 4xx status code
func (o *ListAPISessionsBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list Api sessions bad request response has a 5xx status code
func (o *ListAPISessionsBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list Api sessions bad request response a status code equal to that given
func (o *ListAPISessionsBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the list Api sessions bad request response
func (o *ListAPISessionsBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *ListAPISessionsBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsBadRequest %s", 400, payload)
}

func (o *ListAPISessionsBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsBadRequest %s", 400, payload)
}

func (o *ListAPISessionsBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListAPISessionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPISessionsUnauthorized creates a ListAPISessionsUnauthorized with default headers values
func NewListAPISessionsUnauthorized() *ListAPISessionsUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListAPISessionsUnauthorized{}
}

/*
ListAPISessionsUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListAPISessionsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list Api sessions unauthorized response has a 2xx status code
func (o *ListAPISessionsUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list Api sessions unauthorized response has a 3xx status code
func (o *ListAPISessionsUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list Api sessions unauthorized response has a 4xx status code
func (o *ListAPISessionsUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list Api sessions unauthorized response has a 5xx status code
func (o *ListAPISessionsUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list Api sessions unauthorized response a status code equal to that given
func (o *ListAPISessionsUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list Api sessions unauthorized response
func (o *ListAPISessionsUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListAPISessionsUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsUnauthorized %s", 401, payload)
}

func (o *ListAPISessionsUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsUnauthorized %s", 401, payload)
}

func (o *ListAPISessionsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListAPISessionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPISessionsTooManyRequests creates a ListAPISessionsTooManyRequests with default headers values
func NewListAPISessionsTooManyRequests() *ListAPISessionsTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListAPISessionsTooManyRequests{}
}

/*
ListAPISessionsTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListAPISessionsTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list Api sessions too many requests response has a 2xx status code
func (o *ListAPISessionsTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list Api sessions too many requests response has a 3xx status code
func (o *ListAPISessionsTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list Api sessions too many requests response has a 4xx status code
func (o *ListAPISessionsTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list Api sessions too many requests response has a 5xx status code
func (o *ListAPISessionsTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list Api sessions too many requests response a status code equal to that given
func (o *ListAPISessionsTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list Api sessions too many requests response
func (o *ListAPISessionsTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListAPISessionsTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsTooManyRequests %s", 429, payload)
}

func (o *ListAPISessionsTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsTooManyRequests %s", 429, payload)
}

func (o *ListAPISessionsTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListAPISessionsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAPISessionsServiceUnavailable creates a ListAPISessionsServiceUnavailable with default headers values
func NewListAPISessionsServiceUnavailable() *ListAPISessionsServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListAPISessionsServiceUnavailable{}
}

/*
ListAPISessionsServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListAPISessionsServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list Api sessions service unavailable response has a 2xx status code
func (o *ListAPISessionsServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list Api sessions service unavailable response has a 3xx status code
func (o *ListAPISessionsServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list Api sessions service unavailable response has a 4xx status code
func (o *ListAPISessionsServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list Api sessions service unavailable response has a 5xx status code
func (o *ListAPISessionsServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list Api sessions service unavailable response a status code equal to that given
func (o *ListAPISessionsServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list Api sessions service unavailable response
func (o *ListAPISessionsServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListAPISessionsServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *ListAPISessionsServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api-sessions][%d] listApiSessionsServiceUnavailable %s", 503, payload)
}

func (o *ListAPISessionsServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListAPISessionsServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
