// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package role_attributes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListEdgeRouterRoleAttributesReader is a Reader for the ListEdgeRouterRoleAttributes structure.
type ListEdgeRouterRoleAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEdgeRouterRoleAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListEdgeRouterRoleAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListEdgeRouterRoleAttributesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListEdgeRouterRoleAttributesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListEdgeRouterRoleAttributesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListEdgeRouterRoleAttributesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /edge-router-role-attributes] listEdgeRouterRoleAttributes", response, response.Code())
	}
}

// NewListEdgeRouterRoleAttributesOK creates a ListEdgeRouterRoleAttributesOK with default headers values
func NewListEdgeRouterRoleAttributesOK() *ListEdgeRouterRoleAttributesOK {
    logtrace.LogWithFunctionName()
	return &ListEdgeRouterRoleAttributesOK{}
}

/*
ListEdgeRouterRoleAttributesOK describes a response with status code 200, with default header values.

A list of role attributes
*/
type ListEdgeRouterRoleAttributesOK struct {
	Payload *rest_model.ListRoleAttributesEnvelope
}

// IsSuccess returns true when this list edge router role attributes o k response has a 2xx status code
func (o *ListEdgeRouterRoleAttributesOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list edge router role attributes o k response has a 3xx status code
func (o *ListEdgeRouterRoleAttributesOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list edge router role attributes o k response has a 4xx status code
func (o *ListEdgeRouterRoleAttributesOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list edge router role attributes o k response has a 5xx status code
func (o *ListEdgeRouterRoleAttributesOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list edge router role attributes o k response a status code equal to that given
func (o *ListEdgeRouterRoleAttributesOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list edge router role attributes o k response
func (o *ListEdgeRouterRoleAttributesOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListEdgeRouterRoleAttributesOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesOK %s", 200, payload)
}

func (o *ListEdgeRouterRoleAttributesOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesOK %s", 200, payload)
}

func (o *ListEdgeRouterRoleAttributesOK) GetPayload() *rest_model.ListRoleAttributesEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListEdgeRouterRoleAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListRoleAttributesEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterRoleAttributesBadRequest creates a ListEdgeRouterRoleAttributesBadRequest with default headers values
func NewListEdgeRouterRoleAttributesBadRequest() *ListEdgeRouterRoleAttributesBadRequest {
    logtrace.LogWithFunctionName()
	return &ListEdgeRouterRoleAttributesBadRequest{}
}

/*
ListEdgeRouterRoleAttributesBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type ListEdgeRouterRoleAttributesBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list edge router role attributes bad request response has a 2xx status code
func (o *ListEdgeRouterRoleAttributesBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list edge router role attributes bad request response has a 3xx status code
func (o *ListEdgeRouterRoleAttributesBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list edge router role attributes bad request response has a 4xx status code
func (o *ListEdgeRouterRoleAttributesBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list edge router role attributes bad request response has a 5xx status code
func (o *ListEdgeRouterRoleAttributesBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list edge router role attributes bad request response a status code equal to that given
func (o *ListEdgeRouterRoleAttributesBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the list edge router role attributes bad request response
func (o *ListEdgeRouterRoleAttributesBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *ListEdgeRouterRoleAttributesBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesBadRequest %s", 400, payload)
}

func (o *ListEdgeRouterRoleAttributesBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesBadRequest %s", 400, payload)
}

func (o *ListEdgeRouterRoleAttributesBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListEdgeRouterRoleAttributesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterRoleAttributesUnauthorized creates a ListEdgeRouterRoleAttributesUnauthorized with default headers values
func NewListEdgeRouterRoleAttributesUnauthorized() *ListEdgeRouterRoleAttributesUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListEdgeRouterRoleAttributesUnauthorized{}
}

/*
ListEdgeRouterRoleAttributesUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListEdgeRouterRoleAttributesUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list edge router role attributes unauthorized response has a 2xx status code
func (o *ListEdgeRouterRoleAttributesUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list edge router role attributes unauthorized response has a 3xx status code
func (o *ListEdgeRouterRoleAttributesUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list edge router role attributes unauthorized response has a 4xx status code
func (o *ListEdgeRouterRoleAttributesUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list edge router role attributes unauthorized response has a 5xx status code
func (o *ListEdgeRouterRoleAttributesUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list edge router role attributes unauthorized response a status code equal to that given
func (o *ListEdgeRouterRoleAttributesUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list edge router role attributes unauthorized response
func (o *ListEdgeRouterRoleAttributesUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListEdgeRouterRoleAttributesUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesUnauthorized %s", 401, payload)
}

func (o *ListEdgeRouterRoleAttributesUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesUnauthorized %s", 401, payload)
}

func (o *ListEdgeRouterRoleAttributesUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListEdgeRouterRoleAttributesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterRoleAttributesTooManyRequests creates a ListEdgeRouterRoleAttributesTooManyRequests with default headers values
func NewListEdgeRouterRoleAttributesTooManyRequests() *ListEdgeRouterRoleAttributesTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListEdgeRouterRoleAttributesTooManyRequests{}
}

/*
ListEdgeRouterRoleAttributesTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListEdgeRouterRoleAttributesTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list edge router role attributes too many requests response has a 2xx status code
func (o *ListEdgeRouterRoleAttributesTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list edge router role attributes too many requests response has a 3xx status code
func (o *ListEdgeRouterRoleAttributesTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list edge router role attributes too many requests response has a 4xx status code
func (o *ListEdgeRouterRoleAttributesTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list edge router role attributes too many requests response has a 5xx status code
func (o *ListEdgeRouterRoleAttributesTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list edge router role attributes too many requests response a status code equal to that given
func (o *ListEdgeRouterRoleAttributesTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list edge router role attributes too many requests response
func (o *ListEdgeRouterRoleAttributesTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListEdgeRouterRoleAttributesTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesTooManyRequests %s", 429, payload)
}

func (o *ListEdgeRouterRoleAttributesTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesTooManyRequests %s", 429, payload)
}

func (o *ListEdgeRouterRoleAttributesTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListEdgeRouterRoleAttributesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterRoleAttributesServiceUnavailable creates a ListEdgeRouterRoleAttributesServiceUnavailable with default headers values
func NewListEdgeRouterRoleAttributesServiceUnavailable() *ListEdgeRouterRoleAttributesServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListEdgeRouterRoleAttributesServiceUnavailable{}
}

/*
ListEdgeRouterRoleAttributesServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListEdgeRouterRoleAttributesServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list edge router role attributes service unavailable response has a 2xx status code
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list edge router role attributes service unavailable response has a 3xx status code
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list edge router role attributes service unavailable response has a 4xx status code
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list edge router role attributes service unavailable response has a 5xx status code
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list edge router role attributes service unavailable response a status code equal to that given
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list edge router role attributes service unavailable response
func (o *ListEdgeRouterRoleAttributesServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListEdgeRouterRoleAttributesServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesServiceUnavailable %s", 503, payload)
}

func (o *ListEdgeRouterRoleAttributesServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /edge-router-role-attributes][%d] listEdgeRouterRoleAttributesServiceUnavailable %s", 503, payload)
}

func (o *ListEdgeRouterRoleAttributesServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListEdgeRouterRoleAttributesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
