// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package external_jwt_signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// PatchExternalJWTSignerReader is a Reader for the PatchExternalJWTSigner structure.
type PatchExternalJWTSignerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchExternalJWTSignerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewPatchExternalJWTSignerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchExternalJWTSignerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchExternalJWTSignerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchExternalJWTSignerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPatchExternalJWTSignerTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPatchExternalJWTSignerServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /external-jwt-signers/{id}] patchExternalJwtSigner", response, response.Code())
	}
}

// NewPatchExternalJWTSignerOK creates a PatchExternalJWTSignerOK with default headers values
func NewPatchExternalJWTSignerOK() *PatchExternalJWTSignerOK {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerOK{}
}

/*
PatchExternalJWTSignerOK describes a response with status code 200, with default header values.

The patch request was successful and the resource has been altered
*/
type PatchExternalJWTSignerOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this patch external Jwt signer o k response has a 2xx status code
func (o *PatchExternalJWTSignerOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this patch external Jwt signer o k response has a 3xx status code
func (o *PatchExternalJWTSignerOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer o k response has a 4xx status code
func (o *PatchExternalJWTSignerOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this patch external Jwt signer o k response has a 5xx status code
func (o *PatchExternalJWTSignerOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this patch external Jwt signer o k response a status code equal to that given
func (o *PatchExternalJWTSignerOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the patch external Jwt signer o k response
func (o *PatchExternalJWTSignerOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *PatchExternalJWTSignerOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerOK %s", 200, payload)
}

func (o *PatchExternalJWTSignerOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerOK %s", 200, payload)
}

func (o *PatchExternalJWTSignerOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchExternalJWTSignerBadRequest creates a PatchExternalJWTSignerBadRequest with default headers values
func NewPatchExternalJWTSignerBadRequest() *PatchExternalJWTSignerBadRequest {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerBadRequest{}
}

/*
PatchExternalJWTSignerBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type PatchExternalJWTSignerBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this patch external Jwt signer bad request response has a 2xx status code
func (o *PatchExternalJWTSignerBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this patch external Jwt signer bad request response has a 3xx status code
func (o *PatchExternalJWTSignerBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer bad request response has a 4xx status code
func (o *PatchExternalJWTSignerBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this patch external Jwt signer bad request response has a 5xx status code
func (o *PatchExternalJWTSignerBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this patch external Jwt signer bad request response a status code equal to that given
func (o *PatchExternalJWTSignerBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the patch external Jwt signer bad request response
func (o *PatchExternalJWTSignerBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *PatchExternalJWTSignerBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerBadRequest %s", 400, payload)
}

func (o *PatchExternalJWTSignerBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerBadRequest %s", 400, payload)
}

func (o *PatchExternalJWTSignerBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchExternalJWTSignerUnauthorized creates a PatchExternalJWTSignerUnauthorized with default headers values
func NewPatchExternalJWTSignerUnauthorized() *PatchExternalJWTSignerUnauthorized {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerUnauthorized{}
}

/*
PatchExternalJWTSignerUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type PatchExternalJWTSignerUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this patch external Jwt signer unauthorized response has a 2xx status code
func (o *PatchExternalJWTSignerUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this patch external Jwt signer unauthorized response has a 3xx status code
func (o *PatchExternalJWTSignerUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer unauthorized response has a 4xx status code
func (o *PatchExternalJWTSignerUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this patch external Jwt signer unauthorized response has a 5xx status code
func (o *PatchExternalJWTSignerUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this patch external Jwt signer unauthorized response a status code equal to that given
func (o *PatchExternalJWTSignerUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the patch external Jwt signer unauthorized response
func (o *PatchExternalJWTSignerUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *PatchExternalJWTSignerUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerUnauthorized %s", 401, payload)
}

func (o *PatchExternalJWTSignerUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerUnauthorized %s", 401, payload)
}

func (o *PatchExternalJWTSignerUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchExternalJWTSignerNotFound creates a PatchExternalJWTSignerNotFound with default headers values
func NewPatchExternalJWTSignerNotFound() *PatchExternalJWTSignerNotFound {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerNotFound{}
}

/*
PatchExternalJWTSignerNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type PatchExternalJWTSignerNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this patch external Jwt signer not found response has a 2xx status code
func (o *PatchExternalJWTSignerNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this patch external Jwt signer not found response has a 3xx status code
func (o *PatchExternalJWTSignerNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer not found response has a 4xx status code
func (o *PatchExternalJWTSignerNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this patch external Jwt signer not found response has a 5xx status code
func (o *PatchExternalJWTSignerNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this patch external Jwt signer not found response a status code equal to that given
func (o *PatchExternalJWTSignerNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the patch external Jwt signer not found response
func (o *PatchExternalJWTSignerNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *PatchExternalJWTSignerNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerNotFound %s", 404, payload)
}

func (o *PatchExternalJWTSignerNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerNotFound %s", 404, payload)
}

func (o *PatchExternalJWTSignerNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchExternalJWTSignerTooManyRequests creates a PatchExternalJWTSignerTooManyRequests with default headers values
func NewPatchExternalJWTSignerTooManyRequests() *PatchExternalJWTSignerTooManyRequests {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerTooManyRequests{}
}

/*
PatchExternalJWTSignerTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type PatchExternalJWTSignerTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this patch external Jwt signer too many requests response has a 2xx status code
func (o *PatchExternalJWTSignerTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this patch external Jwt signer too many requests response has a 3xx status code
func (o *PatchExternalJWTSignerTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer too many requests response has a 4xx status code
func (o *PatchExternalJWTSignerTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this patch external Jwt signer too many requests response has a 5xx status code
func (o *PatchExternalJWTSignerTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this patch external Jwt signer too many requests response a status code equal to that given
func (o *PatchExternalJWTSignerTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the patch external Jwt signer too many requests response
func (o *PatchExternalJWTSignerTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *PatchExternalJWTSignerTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerTooManyRequests %s", 429, payload)
}

func (o *PatchExternalJWTSignerTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerTooManyRequests %s", 429, payload)
}

func (o *PatchExternalJWTSignerTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchExternalJWTSignerServiceUnavailable creates a PatchExternalJWTSignerServiceUnavailable with default headers values
func NewPatchExternalJWTSignerServiceUnavailable() *PatchExternalJWTSignerServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &PatchExternalJWTSignerServiceUnavailable{}
}

/*
PatchExternalJWTSignerServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type PatchExternalJWTSignerServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this patch external Jwt signer service unavailable response has a 2xx status code
func (o *PatchExternalJWTSignerServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this patch external Jwt signer service unavailable response has a 3xx status code
func (o *PatchExternalJWTSignerServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this patch external Jwt signer service unavailable response has a 4xx status code
func (o *PatchExternalJWTSignerServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this patch external Jwt signer service unavailable response has a 5xx status code
func (o *PatchExternalJWTSignerServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this patch external Jwt signer service unavailable response a status code equal to that given
func (o *PatchExternalJWTSignerServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the patch external Jwt signer service unavailable response
func (o *PatchExternalJWTSignerServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *PatchExternalJWTSignerServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerServiceUnavailable %s", 503, payload)
}

func (o *PatchExternalJWTSignerServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /external-jwt-signers/{id}][%d] patchExternalJwtSignerServiceUnavailable %s", 503, payload)
}

func (o *PatchExternalJWTSignerServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *PatchExternalJWTSignerServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
