// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package external_jwt_signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// UpdateExternalJWTSignerReader is a Reader for the UpdateExternalJWTSigner structure.
type UpdateExternalJWTSignerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateExternalJWTSignerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewUpdateExternalJWTSignerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateExternalJWTSignerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateExternalJWTSignerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateExternalJWTSignerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateExternalJWTSignerTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUpdateExternalJWTSignerServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /external-jwt-signers/{id}] updateExternalJwtSigner", response, response.Code())
	}
}

// NewUpdateExternalJWTSignerOK creates a UpdateExternalJWTSignerOK with default headers values
func NewUpdateExternalJWTSignerOK() *UpdateExternalJWTSignerOK {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerOK{}
}

/*
UpdateExternalJWTSignerOK describes a response with status code 200, with default header values.

The update request was successful and the resource has been altered
*/
type UpdateExternalJWTSignerOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this update external Jwt signer o k response has a 2xx status code
func (o *UpdateExternalJWTSignerOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this update external Jwt signer o k response has a 3xx status code
func (o *UpdateExternalJWTSignerOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer o k response has a 4xx status code
func (o *UpdateExternalJWTSignerOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this update external Jwt signer o k response has a 5xx status code
func (o *UpdateExternalJWTSignerOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update external Jwt signer o k response a status code equal to that given
func (o *UpdateExternalJWTSignerOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the update external Jwt signer o k response
func (o *UpdateExternalJWTSignerOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *UpdateExternalJWTSignerOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerOK %s", 200, payload)
}

func (o *UpdateExternalJWTSignerOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerOK %s", 200, payload)
}

func (o *UpdateExternalJWTSignerOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateExternalJWTSignerBadRequest creates a UpdateExternalJWTSignerBadRequest with default headers values
func NewUpdateExternalJWTSignerBadRequest() *UpdateExternalJWTSignerBadRequest {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerBadRequest{}
}

/*
UpdateExternalJWTSignerBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type UpdateExternalJWTSignerBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update external Jwt signer bad request response has a 2xx status code
func (o *UpdateExternalJWTSignerBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update external Jwt signer bad request response has a 3xx status code
func (o *UpdateExternalJWTSignerBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer bad request response has a 4xx status code
func (o *UpdateExternalJWTSignerBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update external Jwt signer bad request response has a 5xx status code
func (o *UpdateExternalJWTSignerBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update external Jwt signer bad request response a status code equal to that given
func (o *UpdateExternalJWTSignerBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the update external Jwt signer bad request response
func (o *UpdateExternalJWTSignerBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *UpdateExternalJWTSignerBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerBadRequest %s", 400, payload)
}

func (o *UpdateExternalJWTSignerBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerBadRequest %s", 400, payload)
}

func (o *UpdateExternalJWTSignerBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateExternalJWTSignerUnauthorized creates a UpdateExternalJWTSignerUnauthorized with default headers values
func NewUpdateExternalJWTSignerUnauthorized() *UpdateExternalJWTSignerUnauthorized {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerUnauthorized{}
}

/*
UpdateExternalJWTSignerUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type UpdateExternalJWTSignerUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update external Jwt signer unauthorized response has a 2xx status code
func (o *UpdateExternalJWTSignerUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update external Jwt signer unauthorized response has a 3xx status code
func (o *UpdateExternalJWTSignerUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer unauthorized response has a 4xx status code
func (o *UpdateExternalJWTSignerUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update external Jwt signer unauthorized response has a 5xx status code
func (o *UpdateExternalJWTSignerUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update external Jwt signer unauthorized response a status code equal to that given
func (o *UpdateExternalJWTSignerUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the update external Jwt signer unauthorized response
func (o *UpdateExternalJWTSignerUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *UpdateExternalJWTSignerUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerUnauthorized %s", 401, payload)
}

func (o *UpdateExternalJWTSignerUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerUnauthorized %s", 401, payload)
}

func (o *UpdateExternalJWTSignerUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateExternalJWTSignerNotFound creates a UpdateExternalJWTSignerNotFound with default headers values
func NewUpdateExternalJWTSignerNotFound() *UpdateExternalJWTSignerNotFound {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerNotFound{}
}

/*
UpdateExternalJWTSignerNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type UpdateExternalJWTSignerNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update external Jwt signer not found response has a 2xx status code
func (o *UpdateExternalJWTSignerNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update external Jwt signer not found response has a 3xx status code
func (o *UpdateExternalJWTSignerNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer not found response has a 4xx status code
func (o *UpdateExternalJWTSignerNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update external Jwt signer not found response has a 5xx status code
func (o *UpdateExternalJWTSignerNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update external Jwt signer not found response a status code equal to that given
func (o *UpdateExternalJWTSignerNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the update external Jwt signer not found response
func (o *UpdateExternalJWTSignerNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *UpdateExternalJWTSignerNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerNotFound %s", 404, payload)
}

func (o *UpdateExternalJWTSignerNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerNotFound %s", 404, payload)
}

func (o *UpdateExternalJWTSignerNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateExternalJWTSignerTooManyRequests creates a UpdateExternalJWTSignerTooManyRequests with default headers values
func NewUpdateExternalJWTSignerTooManyRequests() *UpdateExternalJWTSignerTooManyRequests {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerTooManyRequests{}
}

/*
UpdateExternalJWTSignerTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type UpdateExternalJWTSignerTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update external Jwt signer too many requests response has a 2xx status code
func (o *UpdateExternalJWTSignerTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update external Jwt signer too many requests response has a 3xx status code
func (o *UpdateExternalJWTSignerTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer too many requests response has a 4xx status code
func (o *UpdateExternalJWTSignerTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update external Jwt signer too many requests response has a 5xx status code
func (o *UpdateExternalJWTSignerTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update external Jwt signer too many requests response a status code equal to that given
func (o *UpdateExternalJWTSignerTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the update external Jwt signer too many requests response
func (o *UpdateExternalJWTSignerTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *UpdateExternalJWTSignerTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerTooManyRequests %s", 429, payload)
}

func (o *UpdateExternalJWTSignerTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerTooManyRequests %s", 429, payload)
}

func (o *UpdateExternalJWTSignerTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateExternalJWTSignerServiceUnavailable creates a UpdateExternalJWTSignerServiceUnavailable with default headers values
func NewUpdateExternalJWTSignerServiceUnavailable() *UpdateExternalJWTSignerServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &UpdateExternalJWTSignerServiceUnavailable{}
}

/*
UpdateExternalJWTSignerServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type UpdateExternalJWTSignerServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update external Jwt signer service unavailable response has a 2xx status code
func (o *UpdateExternalJWTSignerServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update external Jwt signer service unavailable response has a 3xx status code
func (o *UpdateExternalJWTSignerServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update external Jwt signer service unavailable response has a 4xx status code
func (o *UpdateExternalJWTSignerServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this update external Jwt signer service unavailable response has a 5xx status code
func (o *UpdateExternalJWTSignerServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this update external Jwt signer service unavailable response a status code equal to that given
func (o *UpdateExternalJWTSignerServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the update external Jwt signer service unavailable response
func (o *UpdateExternalJWTSignerServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *UpdateExternalJWTSignerServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerServiceUnavailable %s", 503, payload)
}

func (o *UpdateExternalJWTSignerServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /external-jwt-signers/{id}][%d] updateExternalJwtSignerServiceUnavailable %s", 503, payload)
}

func (o *UpdateExternalJWTSignerServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateExternalJWTSignerServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
