// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// CreateTransitRouterReader is a Reader for the CreateTransitRouter structure.
type CreateTransitRouterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTransitRouterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 201:
		result := NewCreateTransitRouterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateTransitRouterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateTransitRouterUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCreateTransitRouterTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewCreateTransitRouterServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /transit-routers] createTransitRouter", response, response.Code())
	}
}

// NewCreateTransitRouterCreated creates a CreateTransitRouterCreated with default headers values
func NewCreateTransitRouterCreated() *CreateTransitRouterCreated {
    logtrace.LogWithFunctionName()
	return &CreateTransitRouterCreated{}
}

/*
CreateTransitRouterCreated describes a response with status code 201, with default header values.

The create request was successful and the resource has been added at the following location
*/
type CreateTransitRouterCreated struct {
	Payload *rest_model.CreateEnvelope
}

// IsSuccess returns true when this create transit router created response has a 2xx status code
func (o *CreateTransitRouterCreated) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this create transit router created response has a 3xx status code
func (o *CreateTransitRouterCreated) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create transit router created response has a 4xx status code
func (o *CreateTransitRouterCreated) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this create transit router created response has a 5xx status code
func (o *CreateTransitRouterCreated) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create transit router created response a status code equal to that given
func (o *CreateTransitRouterCreated) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 201
}

// Code gets the status code for the create transit router created response
func (o *CreateTransitRouterCreated) Code() int {
    logtrace.LogWithFunctionName()
	return 201
}

func (o *CreateTransitRouterCreated) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterCreated %s", 201, payload)
}

func (o *CreateTransitRouterCreated) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterCreated %s", 201, payload)
}

func (o *CreateTransitRouterCreated) GetPayload() *rest_model.CreateEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateTransitRouterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.CreateEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTransitRouterBadRequest creates a CreateTransitRouterBadRequest with default headers values
func NewCreateTransitRouterBadRequest() *CreateTransitRouterBadRequest {
    logtrace.LogWithFunctionName()
	return &CreateTransitRouterBadRequest{}
}

/*
CreateTransitRouterBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type CreateTransitRouterBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create transit router bad request response has a 2xx status code
func (o *CreateTransitRouterBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create transit router bad request response has a 3xx status code
func (o *CreateTransitRouterBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create transit router bad request response has a 4xx status code
func (o *CreateTransitRouterBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create transit router bad request response has a 5xx status code
func (o *CreateTransitRouterBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create transit router bad request response a status code equal to that given
func (o *CreateTransitRouterBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the create transit router bad request response
func (o *CreateTransitRouterBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *CreateTransitRouterBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterBadRequest %s", 400, payload)
}

func (o *CreateTransitRouterBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterBadRequest %s", 400, payload)
}

func (o *CreateTransitRouterBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateTransitRouterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTransitRouterUnauthorized creates a CreateTransitRouterUnauthorized with default headers values
func NewCreateTransitRouterUnauthorized() *CreateTransitRouterUnauthorized {
    logtrace.LogWithFunctionName()
	return &CreateTransitRouterUnauthorized{}
}

/*
CreateTransitRouterUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type CreateTransitRouterUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create transit router unauthorized response has a 2xx status code
func (o *CreateTransitRouterUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create transit router unauthorized response has a 3xx status code
func (o *CreateTransitRouterUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create transit router unauthorized response has a 4xx status code
func (o *CreateTransitRouterUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create transit router unauthorized response has a 5xx status code
func (o *CreateTransitRouterUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create transit router unauthorized response a status code equal to that given
func (o *CreateTransitRouterUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the create transit router unauthorized response
func (o *CreateTransitRouterUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *CreateTransitRouterUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterUnauthorized %s", 401, payload)
}

func (o *CreateTransitRouterUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterUnauthorized %s", 401, payload)
}

func (o *CreateTransitRouterUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateTransitRouterUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTransitRouterTooManyRequests creates a CreateTransitRouterTooManyRequests with default headers values
func NewCreateTransitRouterTooManyRequests() *CreateTransitRouterTooManyRequests {
    logtrace.LogWithFunctionName()
	return &CreateTransitRouterTooManyRequests{}
}

/*
CreateTransitRouterTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type CreateTransitRouterTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create transit router too many requests response has a 2xx status code
func (o *CreateTransitRouterTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create transit router too many requests response has a 3xx status code
func (o *CreateTransitRouterTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create transit router too many requests response has a 4xx status code
func (o *CreateTransitRouterTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this create transit router too many requests response has a 5xx status code
func (o *CreateTransitRouterTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this create transit router too many requests response a status code equal to that given
func (o *CreateTransitRouterTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the create transit router too many requests response
func (o *CreateTransitRouterTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *CreateTransitRouterTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterTooManyRequests %s", 429, payload)
}

func (o *CreateTransitRouterTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterTooManyRequests %s", 429, payload)
}

func (o *CreateTransitRouterTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateTransitRouterTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTransitRouterServiceUnavailable creates a CreateTransitRouterServiceUnavailable with default headers values
func NewCreateTransitRouterServiceUnavailable() *CreateTransitRouterServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &CreateTransitRouterServiceUnavailable{}
}

/*
CreateTransitRouterServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type CreateTransitRouterServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this create transit router service unavailable response has a 2xx status code
func (o *CreateTransitRouterServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this create transit router service unavailable response has a 3xx status code
func (o *CreateTransitRouterServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this create transit router service unavailable response has a 4xx status code
func (o *CreateTransitRouterServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this create transit router service unavailable response has a 5xx status code
func (o *CreateTransitRouterServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this create transit router service unavailable response a status code equal to that given
func (o *CreateTransitRouterServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the create transit router service unavailable response
func (o *CreateTransitRouterServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *CreateTransitRouterServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterServiceUnavailable %s", 503, payload)
}

func (o *CreateTransitRouterServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /transit-routers][%d] createTransitRouterServiceUnavailable %s", 503, payload)
}

func (o *CreateTransitRouterServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CreateTransitRouterServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
