// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package service_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListServicePolicyPostureChecksReader is a Reader for the ListServicePolicyPostureChecks structure.
type ListServicePolicyPostureChecksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListServicePolicyPostureChecksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListServicePolicyPostureChecksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListServicePolicyPostureChecksBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListServicePolicyPostureChecksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListServicePolicyPostureChecksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListServicePolicyPostureChecksServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /service-policies/{id}/posture-checks] listServicePolicyPostureChecks", response, response.Code())
	}
}

// NewListServicePolicyPostureChecksOK creates a ListServicePolicyPostureChecksOK with default headers values
func NewListServicePolicyPostureChecksOK() *ListServicePolicyPostureChecksOK {
    logtrace.LogWithFunctionName()
	return &ListServicePolicyPostureChecksOK{}
}

/*
ListServicePolicyPostureChecksOK describes a response with status code 200, with default header values.

A list of posture checks
*/
type ListServicePolicyPostureChecksOK struct {
	Payload *rest_model.ListPostureCheckEnvelope
}

// IsSuccess returns true when this list service policy posture checks o k response has a 2xx status code
func (o *ListServicePolicyPostureChecksOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list service policy posture checks o k response has a 3xx status code
func (o *ListServicePolicyPostureChecksOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list service policy posture checks o k response has a 4xx status code
func (o *ListServicePolicyPostureChecksOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list service policy posture checks o k response has a 5xx status code
func (o *ListServicePolicyPostureChecksOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list service policy posture checks o k response a status code equal to that given
func (o *ListServicePolicyPostureChecksOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list service policy posture checks o k response
func (o *ListServicePolicyPostureChecksOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListServicePolicyPostureChecksOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksOK %s", 200, payload)
}

func (o *ListServicePolicyPostureChecksOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksOK %s", 200, payload)
}

func (o *ListServicePolicyPostureChecksOK) GetPayload() *rest_model.ListPostureCheckEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListServicePolicyPostureChecksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListPostureCheckEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServicePolicyPostureChecksBadRequest creates a ListServicePolicyPostureChecksBadRequest with default headers values
func NewListServicePolicyPostureChecksBadRequest() *ListServicePolicyPostureChecksBadRequest {
    logtrace.LogWithFunctionName()
	return &ListServicePolicyPostureChecksBadRequest{}
}

/*
ListServicePolicyPostureChecksBadRequest describes a response with status code 400, with default header values.

The requested resource does not exist
*/
type ListServicePolicyPostureChecksBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list service policy posture checks bad request response has a 2xx status code
func (o *ListServicePolicyPostureChecksBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list service policy posture checks bad request response has a 3xx status code
func (o *ListServicePolicyPostureChecksBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list service policy posture checks bad request response has a 4xx status code
func (o *ListServicePolicyPostureChecksBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list service policy posture checks bad request response has a 5xx status code
func (o *ListServicePolicyPostureChecksBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list service policy posture checks bad request response a status code equal to that given
func (o *ListServicePolicyPostureChecksBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the list service policy posture checks bad request response
func (o *ListServicePolicyPostureChecksBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *ListServicePolicyPostureChecksBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksBadRequest %s", 400, payload)
}

func (o *ListServicePolicyPostureChecksBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksBadRequest %s", 400, payload)
}

func (o *ListServicePolicyPostureChecksBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListServicePolicyPostureChecksBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServicePolicyPostureChecksUnauthorized creates a ListServicePolicyPostureChecksUnauthorized with default headers values
func NewListServicePolicyPostureChecksUnauthorized() *ListServicePolicyPostureChecksUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListServicePolicyPostureChecksUnauthorized{}
}

/*
ListServicePolicyPostureChecksUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListServicePolicyPostureChecksUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list service policy posture checks unauthorized response has a 2xx status code
func (o *ListServicePolicyPostureChecksUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list service policy posture checks unauthorized response has a 3xx status code
func (o *ListServicePolicyPostureChecksUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list service policy posture checks unauthorized response has a 4xx status code
func (o *ListServicePolicyPostureChecksUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list service policy posture checks unauthorized response has a 5xx status code
func (o *ListServicePolicyPostureChecksUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list service policy posture checks unauthorized response a status code equal to that given
func (o *ListServicePolicyPostureChecksUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list service policy posture checks unauthorized response
func (o *ListServicePolicyPostureChecksUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListServicePolicyPostureChecksUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksUnauthorized %s", 401, payload)
}

func (o *ListServicePolicyPostureChecksUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksUnauthorized %s", 401, payload)
}

func (o *ListServicePolicyPostureChecksUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListServicePolicyPostureChecksUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServicePolicyPostureChecksTooManyRequests creates a ListServicePolicyPostureChecksTooManyRequests with default headers values
func NewListServicePolicyPostureChecksTooManyRequests() *ListServicePolicyPostureChecksTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListServicePolicyPostureChecksTooManyRequests{}
}

/*
ListServicePolicyPostureChecksTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListServicePolicyPostureChecksTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list service policy posture checks too many requests response has a 2xx status code
func (o *ListServicePolicyPostureChecksTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list service policy posture checks too many requests response has a 3xx status code
func (o *ListServicePolicyPostureChecksTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list service policy posture checks too many requests response has a 4xx status code
func (o *ListServicePolicyPostureChecksTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list service policy posture checks too many requests response has a 5xx status code
func (o *ListServicePolicyPostureChecksTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list service policy posture checks too many requests response a status code equal to that given
func (o *ListServicePolicyPostureChecksTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list service policy posture checks too many requests response
func (o *ListServicePolicyPostureChecksTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListServicePolicyPostureChecksTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksTooManyRequests %s", 429, payload)
}

func (o *ListServicePolicyPostureChecksTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksTooManyRequests %s", 429, payload)
}

func (o *ListServicePolicyPostureChecksTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListServicePolicyPostureChecksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListServicePolicyPostureChecksServiceUnavailable creates a ListServicePolicyPostureChecksServiceUnavailable with default headers values
func NewListServicePolicyPostureChecksServiceUnavailable() *ListServicePolicyPostureChecksServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListServicePolicyPostureChecksServiceUnavailable{}
}

/*
ListServicePolicyPostureChecksServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListServicePolicyPostureChecksServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list service policy posture checks service unavailable response has a 2xx status code
func (o *ListServicePolicyPostureChecksServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list service policy posture checks service unavailable response has a 3xx status code
func (o *ListServicePolicyPostureChecksServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list service policy posture checks service unavailable response has a 4xx status code
func (o *ListServicePolicyPostureChecksServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list service policy posture checks service unavailable response has a 5xx status code
func (o *ListServicePolicyPostureChecksServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list service policy posture checks service unavailable response a status code equal to that given
func (o *ListServicePolicyPostureChecksServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list service policy posture checks service unavailable response
func (o *ListServicePolicyPostureChecksServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListServicePolicyPostureChecksServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksServiceUnavailable %s", 503, payload)
}

func (o *ListServicePolicyPostureChecksServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /service-policies/{id}/posture-checks][%d] listServicePolicyPostureChecksServiceUnavailable %s", 503, payload)
}

func (o *ListServicePolicyPostureChecksServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListServicePolicyPostureChecksServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
