// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// CheckDataIntegrityReader is a Reader for the CheckDataIntegrity structure.
type CheckDataIntegrityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckDataIntegrityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 202:
		result := NewCheckDataIntegrityAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCheckDataIntegrityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCheckDataIntegrityTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /database/check-data-integrity] checkDataIntegrity", response, response.Code())
	}
}

// NewCheckDataIntegrityAccepted creates a CheckDataIntegrityAccepted with default headers values
func NewCheckDataIntegrityAccepted() *CheckDataIntegrityAccepted {
    logtrace.LogWithFunctionName()
	return &CheckDataIntegrityAccepted{}
}

/*
CheckDataIntegrityAccepted describes a response with status code 202, with default header values.

Base empty response
*/
type CheckDataIntegrityAccepted struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this check data integrity accepted response has a 2xx status code
func (o *CheckDataIntegrityAccepted) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this check data integrity accepted response has a 3xx status code
func (o *CheckDataIntegrityAccepted) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this check data integrity accepted response has a 4xx status code
func (o *CheckDataIntegrityAccepted) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this check data integrity accepted response has a 5xx status code
func (o *CheckDataIntegrityAccepted) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this check data integrity accepted response a status code equal to that given
func (o *CheckDataIntegrityAccepted) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 202
}

// Code gets the status code for the check data integrity accepted response
func (o *CheckDataIntegrityAccepted) Code() int {
    logtrace.LogWithFunctionName()
	return 202
}

func (o *CheckDataIntegrityAccepted) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityAccepted %s", 202, payload)
}

func (o *CheckDataIntegrityAccepted) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityAccepted %s", 202, payload)
}

func (o *CheckDataIntegrityAccepted) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CheckDataIntegrityAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDataIntegrityUnauthorized creates a CheckDataIntegrityUnauthorized with default headers values
func NewCheckDataIntegrityUnauthorized() *CheckDataIntegrityUnauthorized {
    logtrace.LogWithFunctionName()
	return &CheckDataIntegrityUnauthorized{}
}

/*
CheckDataIntegrityUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type CheckDataIntegrityUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this check data integrity unauthorized response has a 2xx status code
func (o *CheckDataIntegrityUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this check data integrity unauthorized response has a 3xx status code
func (o *CheckDataIntegrityUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this check data integrity unauthorized response has a 4xx status code
func (o *CheckDataIntegrityUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this check data integrity unauthorized response has a 5xx status code
func (o *CheckDataIntegrityUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this check data integrity unauthorized response a status code equal to that given
func (o *CheckDataIntegrityUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the check data integrity unauthorized response
func (o *CheckDataIntegrityUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *CheckDataIntegrityUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityUnauthorized %s", 401, payload)
}

func (o *CheckDataIntegrityUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityUnauthorized %s", 401, payload)
}

func (o *CheckDataIntegrityUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CheckDataIntegrityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckDataIntegrityTooManyRequests creates a CheckDataIntegrityTooManyRequests with default headers values
func NewCheckDataIntegrityTooManyRequests() *CheckDataIntegrityTooManyRequests {
    logtrace.LogWithFunctionName()
	return &CheckDataIntegrityTooManyRequests{}
}

/*
CheckDataIntegrityTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type CheckDataIntegrityTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this check data integrity too many requests response has a 2xx status code
func (o *CheckDataIntegrityTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this check data integrity too many requests response has a 3xx status code
func (o *CheckDataIntegrityTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this check data integrity too many requests response has a 4xx status code
func (o *CheckDataIntegrityTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this check data integrity too many requests response has a 5xx status code
func (o *CheckDataIntegrityTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this check data integrity too many requests response a status code equal to that given
func (o *CheckDataIntegrityTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the check data integrity too many requests response
func (o *CheckDataIntegrityTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *CheckDataIntegrityTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityTooManyRequests %s", 429, payload)
}

func (o *CheckDataIntegrityTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /database/check-data-integrity][%d] checkDataIntegrityTooManyRequests %s", 429, payload)
}

func (o *CheckDataIntegrityTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *CheckDataIntegrityTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
