// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// DetailConfigReader is a Reader for the DetailConfig structure.
type DetailConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewDetailConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDetailConfigTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDetailConfigServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /configs/{id}] detailConfig", response, response.Code())
	}
}

// NewDetailConfigOK creates a DetailConfigOK with default headers values
func NewDetailConfigOK() *DetailConfigOK {
    logtrace.LogWithFunctionName()
	return &DetailConfigOK{}
}

/*
DetailConfigOK describes a response with status code 200, with default header values.

A singular config resource
*/
type DetailConfigOK struct {
	Payload *rest_model.DetailConfigEnvelope
}

// IsSuccess returns true when this detail config o k response has a 2xx status code
func (o *DetailConfigOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this detail config o k response has a 3xx status code
func (o *DetailConfigOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail config o k response has a 4xx status code
func (o *DetailConfigOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail config o k response has a 5xx status code
func (o *DetailConfigOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail config o k response a status code equal to that given
func (o *DetailConfigOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the detail config o k response
func (o *DetailConfigOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *DetailConfigOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigOK %s", 200, payload)
}

func (o *DetailConfigOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigOK %s", 200, payload)
}

func (o *DetailConfigOK) GetPayload() *rest_model.DetailConfigEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.DetailConfigEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailConfigUnauthorized creates a DetailConfigUnauthorized with default headers values
func NewDetailConfigUnauthorized() *DetailConfigUnauthorized {
    logtrace.LogWithFunctionName()
	return &DetailConfigUnauthorized{}
}

/*
DetailConfigUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type DetailConfigUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail config unauthorized response has a 2xx status code
func (o *DetailConfigUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail config unauthorized response has a 3xx status code
func (o *DetailConfigUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail config unauthorized response has a 4xx status code
func (o *DetailConfigUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail config unauthorized response has a 5xx status code
func (o *DetailConfigUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail config unauthorized response a status code equal to that given
func (o *DetailConfigUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the detail config unauthorized response
func (o *DetailConfigUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *DetailConfigUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigUnauthorized %s", 401, payload)
}

func (o *DetailConfigUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigUnauthorized %s", 401, payload)
}

func (o *DetailConfigUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailConfigNotFound creates a DetailConfigNotFound with default headers values
func NewDetailConfigNotFound() *DetailConfigNotFound {
    logtrace.LogWithFunctionName()
	return &DetailConfigNotFound{}
}

/*
DetailConfigNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DetailConfigNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail config not found response has a 2xx status code
func (o *DetailConfigNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail config not found response has a 3xx status code
func (o *DetailConfigNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail config not found response has a 4xx status code
func (o *DetailConfigNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail config not found response has a 5xx status code
func (o *DetailConfigNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail config not found response a status code equal to that given
func (o *DetailConfigNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the detail config not found response
func (o *DetailConfigNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *DetailConfigNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigNotFound %s", 404, payload)
}

func (o *DetailConfigNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigNotFound %s", 404, payload)
}

func (o *DetailConfigNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailConfigTooManyRequests creates a DetailConfigTooManyRequests with default headers values
func NewDetailConfigTooManyRequests() *DetailConfigTooManyRequests {
    logtrace.LogWithFunctionName()
	return &DetailConfigTooManyRequests{}
}

/*
DetailConfigTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type DetailConfigTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail config too many requests response has a 2xx status code
func (o *DetailConfigTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail config too many requests response has a 3xx status code
func (o *DetailConfigTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail config too many requests response has a 4xx status code
func (o *DetailConfigTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail config too many requests response has a 5xx status code
func (o *DetailConfigTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail config too many requests response a status code equal to that given
func (o *DetailConfigTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the detail config too many requests response
func (o *DetailConfigTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *DetailConfigTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigTooManyRequests %s", 429, payload)
}

func (o *DetailConfigTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigTooManyRequests %s", 429, payload)
}

func (o *DetailConfigTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailConfigTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailConfigServiceUnavailable creates a DetailConfigServiceUnavailable with default headers values
func NewDetailConfigServiceUnavailable() *DetailConfigServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &DetailConfigServiceUnavailable{}
}

/*
DetailConfigServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type DetailConfigServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail config service unavailable response has a 2xx status code
func (o *DetailConfigServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail config service unavailable response has a 3xx status code
func (o *DetailConfigServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail config service unavailable response has a 4xx status code
func (o *DetailConfigServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail config service unavailable response has a 5xx status code
func (o *DetailConfigServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this detail config service unavailable response a status code equal to that given
func (o *DetailConfigServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the detail config service unavailable response
func (o *DetailConfigServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *DetailConfigServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigServiceUnavailable %s", 503, payload)
}

func (o *DetailConfigServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /configs/{id}][%d] detailConfigServiceUnavailable %s", 503, payload)
}

func (o *DetailConfigServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailConfigServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
