// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListConfigsForConfigTypeReader is a Reader for the ListConfigsForConfigType structure.
type ListConfigsForConfigTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListConfigsForConfigTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListConfigsForConfigTypeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListConfigsForConfigTypeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListConfigsForConfigTypeTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListConfigsForConfigTypeServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /config-types/{id}/configs] listConfigsForConfigType", response, response.Code())
	}
}

// NewListConfigsForConfigTypeOK creates a ListConfigsForConfigTypeOK with default headers values
func NewListConfigsForConfigTypeOK() *ListConfigsForConfigTypeOK {
    logtrace.LogWithFunctionName()
	return &ListConfigsForConfigTypeOK{}
}

/*
ListConfigsForConfigTypeOK describes a response with status code 200, with default header values.

A list of configs
*/
type ListConfigsForConfigTypeOK struct {
	Payload *rest_model.ListConfigsEnvelope
}

// IsSuccess returns true when this list configs for config type o k response has a 2xx status code
func (o *ListConfigsForConfigTypeOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list configs for config type o k response has a 3xx status code
func (o *ListConfigsForConfigTypeOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list configs for config type o k response has a 4xx status code
func (o *ListConfigsForConfigTypeOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list configs for config type o k response has a 5xx status code
func (o *ListConfigsForConfigTypeOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list configs for config type o k response a status code equal to that given
func (o *ListConfigsForConfigTypeOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list configs for config type o k response
func (o *ListConfigsForConfigTypeOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListConfigsForConfigTypeOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeOK %s", 200, payload)
}

func (o *ListConfigsForConfigTypeOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeOK %s", 200, payload)
}

func (o *ListConfigsForConfigTypeOK) GetPayload() *rest_model.ListConfigsEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListConfigsForConfigTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListConfigsEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigsForConfigTypeUnauthorized creates a ListConfigsForConfigTypeUnauthorized with default headers values
func NewListConfigsForConfigTypeUnauthorized() *ListConfigsForConfigTypeUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListConfigsForConfigTypeUnauthorized{}
}

/*
ListConfigsForConfigTypeUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListConfigsForConfigTypeUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list configs for config type unauthorized response has a 2xx status code
func (o *ListConfigsForConfigTypeUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list configs for config type unauthorized response has a 3xx status code
func (o *ListConfigsForConfigTypeUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list configs for config type unauthorized response has a 4xx status code
func (o *ListConfigsForConfigTypeUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list configs for config type unauthorized response has a 5xx status code
func (o *ListConfigsForConfigTypeUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list configs for config type unauthorized response a status code equal to that given
func (o *ListConfigsForConfigTypeUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list configs for config type unauthorized response
func (o *ListConfigsForConfigTypeUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListConfigsForConfigTypeUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeUnauthorized %s", 401, payload)
}

func (o *ListConfigsForConfigTypeUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeUnauthorized %s", 401, payload)
}

func (o *ListConfigsForConfigTypeUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListConfigsForConfigTypeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigsForConfigTypeTooManyRequests creates a ListConfigsForConfigTypeTooManyRequests with default headers values
func NewListConfigsForConfigTypeTooManyRequests() *ListConfigsForConfigTypeTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListConfigsForConfigTypeTooManyRequests{}
}

/*
ListConfigsForConfigTypeTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListConfigsForConfigTypeTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list configs for config type too many requests response has a 2xx status code
func (o *ListConfigsForConfigTypeTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list configs for config type too many requests response has a 3xx status code
func (o *ListConfigsForConfigTypeTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list configs for config type too many requests response has a 4xx status code
func (o *ListConfigsForConfigTypeTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list configs for config type too many requests response has a 5xx status code
func (o *ListConfigsForConfigTypeTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list configs for config type too many requests response a status code equal to that given
func (o *ListConfigsForConfigTypeTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list configs for config type too many requests response
func (o *ListConfigsForConfigTypeTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListConfigsForConfigTypeTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeTooManyRequests %s", 429, payload)
}

func (o *ListConfigsForConfigTypeTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeTooManyRequests %s", 429, payload)
}

func (o *ListConfigsForConfigTypeTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListConfigsForConfigTypeTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListConfigsForConfigTypeServiceUnavailable creates a ListConfigsForConfigTypeServiceUnavailable with default headers values
func NewListConfigsForConfigTypeServiceUnavailable() *ListConfigsForConfigTypeServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListConfigsForConfigTypeServiceUnavailable{}
}

/*
ListConfigsForConfigTypeServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListConfigsForConfigTypeServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list configs for config type service unavailable response has a 2xx status code
func (o *ListConfigsForConfigTypeServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list configs for config type service unavailable response has a 3xx status code
func (o *ListConfigsForConfigTypeServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list configs for config type service unavailable response has a 4xx status code
func (o *ListConfigsForConfigTypeServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list configs for config type service unavailable response has a 5xx status code
func (o *ListConfigsForConfigTypeServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list configs for config type service unavailable response a status code equal to that given
func (o *ListConfigsForConfigTypeServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list configs for config type service unavailable response
func (o *ListConfigsForConfigTypeServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListConfigsForConfigTypeServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeServiceUnavailable %s", 503, payload)
}

func (o *ListConfigsForConfigTypeServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /config-types/{id}/configs][%d] listConfigsForConfigTypeServiceUnavailable %s", 503, payload)
}

func (o *ListConfigsForConfigTypeServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListConfigsForConfigTypeServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
