// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// DetailIdentityReader is a Reader for the DetailIdentity structure.
type DetailIdentityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailIdentityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewDetailIdentityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailIdentityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailIdentityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDetailIdentityTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDetailIdentityServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /identities/{id}] detailIdentity", response, response.Code())
	}
}

// NewDetailIdentityOK creates a DetailIdentityOK with default headers values
func NewDetailIdentityOK() *DetailIdentityOK {
    logtrace.LogWithFunctionName()
	return &DetailIdentityOK{}
}

/*
DetailIdentityOK describes a response with status code 200, with default header values.

A single identity
*/
type DetailIdentityOK struct {
	Payload *rest_model.DetailIdentityEnvelope
}

// IsSuccess returns true when this detail identity o k response has a 2xx status code
func (o *DetailIdentityOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this detail identity o k response has a 3xx status code
func (o *DetailIdentityOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail identity o k response has a 4xx status code
func (o *DetailIdentityOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail identity o k response has a 5xx status code
func (o *DetailIdentityOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail identity o k response a status code equal to that given
func (o *DetailIdentityOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the detail identity o k response
func (o *DetailIdentityOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *DetailIdentityOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityOK %s", 200, payload)
}

func (o *DetailIdentityOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityOK %s", 200, payload)
}

func (o *DetailIdentityOK) GetPayload() *rest_model.DetailIdentityEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailIdentityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.DetailIdentityEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailIdentityUnauthorized creates a DetailIdentityUnauthorized with default headers values
func NewDetailIdentityUnauthorized() *DetailIdentityUnauthorized {
    logtrace.LogWithFunctionName()
	return &DetailIdentityUnauthorized{}
}

/*
DetailIdentityUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type DetailIdentityUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail identity unauthorized response has a 2xx status code
func (o *DetailIdentityUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail identity unauthorized response has a 3xx status code
func (o *DetailIdentityUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail identity unauthorized response has a 4xx status code
func (o *DetailIdentityUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail identity unauthorized response has a 5xx status code
func (o *DetailIdentityUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail identity unauthorized response a status code equal to that given
func (o *DetailIdentityUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the detail identity unauthorized response
func (o *DetailIdentityUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *DetailIdentityUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityUnauthorized %s", 401, payload)
}

func (o *DetailIdentityUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityUnauthorized %s", 401, payload)
}

func (o *DetailIdentityUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailIdentityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailIdentityNotFound creates a DetailIdentityNotFound with default headers values
func NewDetailIdentityNotFound() *DetailIdentityNotFound {
    logtrace.LogWithFunctionName()
	return &DetailIdentityNotFound{}
}

/*
DetailIdentityNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type DetailIdentityNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail identity not found response has a 2xx status code
func (o *DetailIdentityNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail identity not found response has a 3xx status code
func (o *DetailIdentityNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail identity not found response has a 4xx status code
func (o *DetailIdentityNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail identity not found response has a 5xx status code
func (o *DetailIdentityNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail identity not found response a status code equal to that given
func (o *DetailIdentityNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the detail identity not found response
func (o *DetailIdentityNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *DetailIdentityNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityNotFound %s", 404, payload)
}

func (o *DetailIdentityNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityNotFound %s", 404, payload)
}

func (o *DetailIdentityNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailIdentityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailIdentityTooManyRequests creates a DetailIdentityTooManyRequests with default headers values
func NewDetailIdentityTooManyRequests() *DetailIdentityTooManyRequests {
    logtrace.LogWithFunctionName()
	return &DetailIdentityTooManyRequests{}
}

/*
DetailIdentityTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type DetailIdentityTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail identity too many requests response has a 2xx status code
func (o *DetailIdentityTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail identity too many requests response has a 3xx status code
func (o *DetailIdentityTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail identity too many requests response has a 4xx status code
func (o *DetailIdentityTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this detail identity too many requests response has a 5xx status code
func (o *DetailIdentityTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this detail identity too many requests response a status code equal to that given
func (o *DetailIdentityTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the detail identity too many requests response
func (o *DetailIdentityTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *DetailIdentityTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityTooManyRequests %s", 429, payload)
}

func (o *DetailIdentityTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityTooManyRequests %s", 429, payload)
}

func (o *DetailIdentityTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailIdentityTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailIdentityServiceUnavailable creates a DetailIdentityServiceUnavailable with default headers values
func NewDetailIdentityServiceUnavailable() *DetailIdentityServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &DetailIdentityServiceUnavailable{}
}

/*
DetailIdentityServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type DetailIdentityServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this detail identity service unavailable response has a 2xx status code
func (o *DetailIdentityServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this detail identity service unavailable response has a 3xx status code
func (o *DetailIdentityServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this detail identity service unavailable response has a 4xx status code
func (o *DetailIdentityServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this detail identity service unavailable response has a 5xx status code
func (o *DetailIdentityServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this detail identity service unavailable response a status code equal to that given
func (o *DetailIdentityServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the detail identity service unavailable response
func (o *DetailIdentityServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *DetailIdentityServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityServiceUnavailable %s", 503, payload)
}

func (o *DetailIdentityServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}][%d] detailIdentityServiceUnavailable %s", 503, payload)
}

func (o *DetailIdentityServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *DetailIdentityServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
