// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// EnableIdentityReader is a Reader for the EnableIdentity structure.
type EnableIdentityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableIdentityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewEnableIdentityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEnableIdentityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEnableIdentityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewEnableIdentityTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEnableIdentityServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /identities/{id}/enable] enableIdentity", response, response.Code())
	}
}

// NewEnableIdentityOK creates a EnableIdentityOK with default headers values
func NewEnableIdentityOK() *EnableIdentityOK {
    logtrace.LogWithFunctionName()
	return &EnableIdentityOK{}
}

/*
EnableIdentityOK describes a response with status code 200, with default header values.

Base empty response
*/
type EnableIdentityOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this enable identity o k response has a 2xx status code
func (o *EnableIdentityOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this enable identity o k response has a 3xx status code
func (o *EnableIdentityOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enable identity o k response has a 4xx status code
func (o *EnableIdentityOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enable identity o k response has a 5xx status code
func (o *EnableIdentityOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enable identity o k response a status code equal to that given
func (o *EnableIdentityOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the enable identity o k response
func (o *EnableIdentityOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *EnableIdentityOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityOK %s", 200, payload)
}

func (o *EnableIdentityOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityOK %s", 200, payload)
}

func (o *EnableIdentityOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnableIdentityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableIdentityUnauthorized creates a EnableIdentityUnauthorized with default headers values
func NewEnableIdentityUnauthorized() *EnableIdentityUnauthorized {
    logtrace.LogWithFunctionName()
	return &EnableIdentityUnauthorized{}
}

/*
EnableIdentityUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type EnableIdentityUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enable identity unauthorized response has a 2xx status code
func (o *EnableIdentityUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enable identity unauthorized response has a 3xx status code
func (o *EnableIdentityUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enable identity unauthorized response has a 4xx status code
func (o *EnableIdentityUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enable identity unauthorized response has a 5xx status code
func (o *EnableIdentityUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enable identity unauthorized response a status code equal to that given
func (o *EnableIdentityUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the enable identity unauthorized response
func (o *EnableIdentityUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *EnableIdentityUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityUnauthorized %s", 401, payload)
}

func (o *EnableIdentityUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityUnauthorized %s", 401, payload)
}

func (o *EnableIdentityUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnableIdentityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableIdentityNotFound creates a EnableIdentityNotFound with default headers values
func NewEnableIdentityNotFound() *EnableIdentityNotFound {
    logtrace.LogWithFunctionName()
	return &EnableIdentityNotFound{}
}

/*
EnableIdentityNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type EnableIdentityNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enable identity not found response has a 2xx status code
func (o *EnableIdentityNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enable identity not found response has a 3xx status code
func (o *EnableIdentityNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enable identity not found response has a 4xx status code
func (o *EnableIdentityNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enable identity not found response has a 5xx status code
func (o *EnableIdentityNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enable identity not found response a status code equal to that given
func (o *EnableIdentityNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the enable identity not found response
func (o *EnableIdentityNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *EnableIdentityNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityNotFound %s", 404, payload)
}

func (o *EnableIdentityNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityNotFound %s", 404, payload)
}

func (o *EnableIdentityNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnableIdentityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableIdentityTooManyRequests creates a EnableIdentityTooManyRequests with default headers values
func NewEnableIdentityTooManyRequests() *EnableIdentityTooManyRequests {
    logtrace.LogWithFunctionName()
	return &EnableIdentityTooManyRequests{}
}

/*
EnableIdentityTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type EnableIdentityTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enable identity too many requests response has a 2xx status code
func (o *EnableIdentityTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enable identity too many requests response has a 3xx status code
func (o *EnableIdentityTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enable identity too many requests response has a 4xx status code
func (o *EnableIdentityTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this enable identity too many requests response has a 5xx status code
func (o *EnableIdentityTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this enable identity too many requests response a status code equal to that given
func (o *EnableIdentityTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the enable identity too many requests response
func (o *EnableIdentityTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *EnableIdentityTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityTooManyRequests %s", 429, payload)
}

func (o *EnableIdentityTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityTooManyRequests %s", 429, payload)
}

func (o *EnableIdentityTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnableIdentityTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableIdentityServiceUnavailable creates a EnableIdentityServiceUnavailable with default headers values
func NewEnableIdentityServiceUnavailable() *EnableIdentityServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &EnableIdentityServiceUnavailable{}
}

/*
EnableIdentityServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type EnableIdentityServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this enable identity service unavailable response has a 2xx status code
func (o *EnableIdentityServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this enable identity service unavailable response has a 3xx status code
func (o *EnableIdentityServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this enable identity service unavailable response has a 4xx status code
func (o *EnableIdentityServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this enable identity service unavailable response has a 5xx status code
func (o *EnableIdentityServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this enable identity service unavailable response a status code equal to that given
func (o *EnableIdentityServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the enable identity service unavailable response
func (o *EnableIdentityServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *EnableIdentityServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityServiceUnavailable %s", 503, payload)
}

func (o *EnableIdentityServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /identities/{id}/enable][%d] enableIdentityServiceUnavailable %s", 503, payload)
}

func (o *EnableIdentityServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *EnableIdentityServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
