// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// ListIdentityServicePoliciesReader is a Reader for the ListIdentityServicePolicies structure.
type ListIdentityServicePoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIdentityServicePoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewListIdentityServicePoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListIdentityServicePoliciesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListIdentityServicePoliciesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewListIdentityServicePoliciesTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewListIdentityServicePoliciesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /identities/{id}/service-policies] listIdentityServicePolicies", response, response.Code())
	}
}

// NewListIdentityServicePoliciesOK creates a ListIdentityServicePoliciesOK with default headers values
func NewListIdentityServicePoliciesOK() *ListIdentityServicePoliciesOK {
    logtrace.LogWithFunctionName()
	return &ListIdentityServicePoliciesOK{}
}

/*
ListIdentityServicePoliciesOK describes a response with status code 200, with default header values.

A list of service policies
*/
type ListIdentityServicePoliciesOK struct {
	Payload *rest_model.ListServicePoliciesEnvelope
}

// IsSuccess returns true when this list identity service policies o k response has a 2xx status code
func (o *ListIdentityServicePoliciesOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this list identity service policies o k response has a 3xx status code
func (o *ListIdentityServicePoliciesOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list identity service policies o k response has a 4xx status code
func (o *ListIdentityServicePoliciesOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list identity service policies o k response has a 5xx status code
func (o *ListIdentityServicePoliciesOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list identity service policies o k response a status code equal to that given
func (o *ListIdentityServicePoliciesOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the list identity service policies o k response
func (o *ListIdentityServicePoliciesOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *ListIdentityServicePoliciesOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesOK %s", 200, payload)
}

func (o *ListIdentityServicePoliciesOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesOK %s", 200, payload)
}

func (o *ListIdentityServicePoliciesOK) GetPayload() *rest_model.ListServicePoliciesEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListIdentityServicePoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.ListServicePoliciesEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIdentityServicePoliciesUnauthorized creates a ListIdentityServicePoliciesUnauthorized with default headers values
func NewListIdentityServicePoliciesUnauthorized() *ListIdentityServicePoliciesUnauthorized {
    logtrace.LogWithFunctionName()
	return &ListIdentityServicePoliciesUnauthorized{}
}

/*
ListIdentityServicePoliciesUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type ListIdentityServicePoliciesUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list identity service policies unauthorized response has a 2xx status code
func (o *ListIdentityServicePoliciesUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list identity service policies unauthorized response has a 3xx status code
func (o *ListIdentityServicePoliciesUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list identity service policies unauthorized response has a 4xx status code
func (o *ListIdentityServicePoliciesUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list identity service policies unauthorized response has a 5xx status code
func (o *ListIdentityServicePoliciesUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list identity service policies unauthorized response a status code equal to that given
func (o *ListIdentityServicePoliciesUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the list identity service policies unauthorized response
func (o *ListIdentityServicePoliciesUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *ListIdentityServicePoliciesUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesUnauthorized %s", 401, payload)
}

func (o *ListIdentityServicePoliciesUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesUnauthorized %s", 401, payload)
}

func (o *ListIdentityServicePoliciesUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListIdentityServicePoliciesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIdentityServicePoliciesNotFound creates a ListIdentityServicePoliciesNotFound with default headers values
func NewListIdentityServicePoliciesNotFound() *ListIdentityServicePoliciesNotFound {
    logtrace.LogWithFunctionName()
	return &ListIdentityServicePoliciesNotFound{}
}

/*
ListIdentityServicePoliciesNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type ListIdentityServicePoliciesNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list identity service policies not found response has a 2xx status code
func (o *ListIdentityServicePoliciesNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list identity service policies not found response has a 3xx status code
func (o *ListIdentityServicePoliciesNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list identity service policies not found response has a 4xx status code
func (o *ListIdentityServicePoliciesNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list identity service policies not found response has a 5xx status code
func (o *ListIdentityServicePoliciesNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list identity service policies not found response a status code equal to that given
func (o *ListIdentityServicePoliciesNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the list identity service policies not found response
func (o *ListIdentityServicePoliciesNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *ListIdentityServicePoliciesNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesNotFound %s", 404, payload)
}

func (o *ListIdentityServicePoliciesNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesNotFound %s", 404, payload)
}

func (o *ListIdentityServicePoliciesNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListIdentityServicePoliciesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIdentityServicePoliciesTooManyRequests creates a ListIdentityServicePoliciesTooManyRequests with default headers values
func NewListIdentityServicePoliciesTooManyRequests() *ListIdentityServicePoliciesTooManyRequests {
    logtrace.LogWithFunctionName()
	return &ListIdentityServicePoliciesTooManyRequests{}
}

/*
ListIdentityServicePoliciesTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type ListIdentityServicePoliciesTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list identity service policies too many requests response has a 2xx status code
func (o *ListIdentityServicePoliciesTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list identity service policies too many requests response has a 3xx status code
func (o *ListIdentityServicePoliciesTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list identity service policies too many requests response has a 4xx status code
func (o *ListIdentityServicePoliciesTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this list identity service policies too many requests response has a 5xx status code
func (o *ListIdentityServicePoliciesTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this list identity service policies too many requests response a status code equal to that given
func (o *ListIdentityServicePoliciesTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the list identity service policies too many requests response
func (o *ListIdentityServicePoliciesTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *ListIdentityServicePoliciesTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesTooManyRequests %s", 429, payload)
}

func (o *ListIdentityServicePoliciesTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesTooManyRequests %s", 429, payload)
}

func (o *ListIdentityServicePoliciesTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListIdentityServicePoliciesTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIdentityServicePoliciesServiceUnavailable creates a ListIdentityServicePoliciesServiceUnavailable with default headers values
func NewListIdentityServicePoliciesServiceUnavailable() *ListIdentityServicePoliciesServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &ListIdentityServicePoliciesServiceUnavailable{}
}

/*
ListIdentityServicePoliciesServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type ListIdentityServicePoliciesServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this list identity service policies service unavailable response has a 2xx status code
func (o *ListIdentityServicePoliciesServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this list identity service policies service unavailable response has a 3xx status code
func (o *ListIdentityServicePoliciesServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this list identity service policies service unavailable response has a 4xx status code
func (o *ListIdentityServicePoliciesServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this list identity service policies service unavailable response has a 5xx status code
func (o *ListIdentityServicePoliciesServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this list identity service policies service unavailable response a status code equal to that given
func (o *ListIdentityServicePoliciesServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the list identity service policies service unavailable response
func (o *ListIdentityServicePoliciesServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *ListIdentityServicePoliciesServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesServiceUnavailable %s", 503, payload)
}

func (o *ListIdentityServicePoliciesServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /identities/{id}/service-policies][%d] listIdentityServicePoliciesServiceUnavailable %s", 503, payload)
}

func (o *ListIdentityServicePoliciesServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *ListIdentityServicePoliciesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
