// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"ztna-core/ztna/logtrace"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"ztna-core/edge-api/rest_model"
)

// UpdateIdentityReader is a Reader for the UpdateIdentity structure.
type UpdateIdentityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateIdentityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
    logtrace.LogWithFunctionName()
	switch response.Code() {
	case 200:
		result := NewUpdateIdentityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateIdentityBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateIdentityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateIdentityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateIdentityTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewUpdateIdentityServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /identities/{id}] updateIdentity", response, response.Code())
	}
}

// NewUpdateIdentityOK creates a UpdateIdentityOK with default headers values
func NewUpdateIdentityOK() *UpdateIdentityOK {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityOK{}
}

/*
UpdateIdentityOK describes a response with status code 200, with default header values.

The update request was successful and the resource has been altered
*/
type UpdateIdentityOK struct {
	Payload *rest_model.Empty
}

// IsSuccess returns true when this update identity o k response has a 2xx status code
func (o *UpdateIdentityOK) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsRedirect returns true when this update identity o k response has a 3xx status code
func (o *UpdateIdentityOK) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity o k response has a 4xx status code
func (o *UpdateIdentityOK) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this update identity o k response has a 5xx status code
func (o *UpdateIdentityOK) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update identity o k response a status code equal to that given
func (o *UpdateIdentityOK) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 200
}

// Code gets the status code for the update identity o k response
func (o *UpdateIdentityOK) Code() int {
    logtrace.LogWithFunctionName()
	return 200
}

func (o *UpdateIdentityOK) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityOK %s", 200, payload)
}

func (o *UpdateIdentityOK) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityOK %s", 200, payload)
}

func (o *UpdateIdentityOK) GetPayload() *rest_model.Empty {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIdentityBadRequest creates a UpdateIdentityBadRequest with default headers values
func NewUpdateIdentityBadRequest() *UpdateIdentityBadRequest {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityBadRequest{}
}

/*
UpdateIdentityBadRequest describes a response with status code 400, with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type UpdateIdentityBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update identity bad request response has a 2xx status code
func (o *UpdateIdentityBadRequest) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update identity bad request response has a 3xx status code
func (o *UpdateIdentityBadRequest) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity bad request response has a 4xx status code
func (o *UpdateIdentityBadRequest) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update identity bad request response has a 5xx status code
func (o *UpdateIdentityBadRequest) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update identity bad request response a status code equal to that given
func (o *UpdateIdentityBadRequest) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 400
}

// Code gets the status code for the update identity bad request response
func (o *UpdateIdentityBadRequest) Code() int {
    logtrace.LogWithFunctionName()
	return 400
}

func (o *UpdateIdentityBadRequest) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityBadRequest %s", 400, payload)
}

func (o *UpdateIdentityBadRequest) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityBadRequest %s", 400, payload)
}

func (o *UpdateIdentityBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIdentityUnauthorized creates a UpdateIdentityUnauthorized with default headers values
func NewUpdateIdentityUnauthorized() *UpdateIdentityUnauthorized {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityUnauthorized{}
}

/*
UpdateIdentityUnauthorized describes a response with status code 401, with default header values.

The supplied session does not have the correct access rights to request this resource
*/
type UpdateIdentityUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update identity unauthorized response has a 2xx status code
func (o *UpdateIdentityUnauthorized) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update identity unauthorized response has a 3xx status code
func (o *UpdateIdentityUnauthorized) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity unauthorized response has a 4xx status code
func (o *UpdateIdentityUnauthorized) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update identity unauthorized response has a 5xx status code
func (o *UpdateIdentityUnauthorized) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update identity unauthorized response a status code equal to that given
func (o *UpdateIdentityUnauthorized) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 401
}

// Code gets the status code for the update identity unauthorized response
func (o *UpdateIdentityUnauthorized) Code() int {
    logtrace.LogWithFunctionName()
	return 401
}

func (o *UpdateIdentityUnauthorized) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityUnauthorized %s", 401, payload)
}

func (o *UpdateIdentityUnauthorized) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityUnauthorized %s", 401, payload)
}

func (o *UpdateIdentityUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIdentityNotFound creates a UpdateIdentityNotFound with default headers values
func NewUpdateIdentityNotFound() *UpdateIdentityNotFound {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityNotFound{}
}

/*
UpdateIdentityNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type UpdateIdentityNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update identity not found response has a 2xx status code
func (o *UpdateIdentityNotFound) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update identity not found response has a 3xx status code
func (o *UpdateIdentityNotFound) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity not found response has a 4xx status code
func (o *UpdateIdentityNotFound) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update identity not found response has a 5xx status code
func (o *UpdateIdentityNotFound) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update identity not found response a status code equal to that given
func (o *UpdateIdentityNotFound) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 404
}

// Code gets the status code for the update identity not found response
func (o *UpdateIdentityNotFound) Code() int {
    logtrace.LogWithFunctionName()
	return 404
}

func (o *UpdateIdentityNotFound) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityNotFound %s", 404, payload)
}

func (o *UpdateIdentityNotFound) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityNotFound %s", 404, payload)
}

func (o *UpdateIdentityNotFound) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIdentityTooManyRequests creates a UpdateIdentityTooManyRequests with default headers values
func NewUpdateIdentityTooManyRequests() *UpdateIdentityTooManyRequests {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityTooManyRequests{}
}

/*
UpdateIdentityTooManyRequests describes a response with status code 429, with default header values.

The resource requested is rate limited and the rate limit has been exceeded
*/
type UpdateIdentityTooManyRequests struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update identity too many requests response has a 2xx status code
func (o *UpdateIdentityTooManyRequests) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update identity too many requests response has a 3xx status code
func (o *UpdateIdentityTooManyRequests) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity too many requests response has a 4xx status code
func (o *UpdateIdentityTooManyRequests) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsServerError returns true when this update identity too many requests response has a 5xx status code
func (o *UpdateIdentityTooManyRequests) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsCode returns true when this update identity too many requests response a status code equal to that given
func (o *UpdateIdentityTooManyRequests) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 429
}

// Code gets the status code for the update identity too many requests response
func (o *UpdateIdentityTooManyRequests) Code() int {
    logtrace.LogWithFunctionName()
	return 429
}

func (o *UpdateIdentityTooManyRequests) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityTooManyRequests %s", 429, payload)
}

func (o *UpdateIdentityTooManyRequests) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityTooManyRequests %s", 429, payload)
}

func (o *UpdateIdentityTooManyRequests) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIdentityServiceUnavailable creates a UpdateIdentityServiceUnavailable with default headers values
func NewUpdateIdentityServiceUnavailable() *UpdateIdentityServiceUnavailable {
    logtrace.LogWithFunctionName()
	return &UpdateIdentityServiceUnavailable{}
}

/*
UpdateIdentityServiceUnavailable describes a response with status code 503, with default header values.

The request could not be completed due to the server being busy or in a temporarily bad state
*/
type UpdateIdentityServiceUnavailable struct {
	Payload *rest_model.APIErrorEnvelope
}

// IsSuccess returns true when this update identity service unavailable response has a 2xx status code
func (o *UpdateIdentityServiceUnavailable) IsSuccess() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsRedirect returns true when this update identity service unavailable response has a 3xx status code
func (o *UpdateIdentityServiceUnavailable) IsRedirect() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsClientError returns true when this update identity service unavailable response has a 4xx status code
func (o *UpdateIdentityServiceUnavailable) IsClientError() bool {
    logtrace.LogWithFunctionName()
	return false
}

// IsServerError returns true when this update identity service unavailable response has a 5xx status code
func (o *UpdateIdentityServiceUnavailable) IsServerError() bool {
    logtrace.LogWithFunctionName()
	return true
}

// IsCode returns true when this update identity service unavailable response a status code equal to that given
func (o *UpdateIdentityServiceUnavailable) IsCode(code int) bool {
    logtrace.LogWithFunctionName()
	return code == 503
}

// Code gets the status code for the update identity service unavailable response
func (o *UpdateIdentityServiceUnavailable) Code() int {
    logtrace.LogWithFunctionName()
	return 503
}

func (o *UpdateIdentityServiceUnavailable) Error() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityServiceUnavailable %s", 503, payload)
}

func (o *UpdateIdentityServiceUnavailable) String() string {
    logtrace.LogWithFunctionName()
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /identities/{id}][%d] updateIdentityServiceUnavailable %s", 503, payload)
}

func (o *UpdateIdentityServiceUnavailable) GetPayload() *rest_model.APIErrorEnvelope {
    logtrace.LogWithFunctionName()
	return o.Payload
}

func (o *UpdateIdentityServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
    logtrace.LogWithFunctionName()

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
